const supermercadoCategories = [
  {
    icon: "🍞",
    iconClass: "icon-1",
    title: "Panadería y bollería",
    text: 'Pan de molde sin gluten, baguettes certificadas y bollería (Schär, Proceli, líneas "Sin Gluten" de supermercado).',
    productos: [
      "Hacendado (Mercadona) — Pan de molde blanco sin gluten",
      "Hacendado (Mercadona) — Baguette sin gluten",
      "Hacendado (Mercadona) — Pan de hamburguesa sin gluten",
      "Schär — Pan de molde (Pan Carré)",
      "Proceli — Pan tradicional sin gluten",
      "Beiker — Pan de molde sin gluten",
      "Adpan — Chapata sin gluten",
      "Carrefour Sin Gluten — Magdalenas y bollería sin gluten",
      "Gerblé — Pan payés con semillas sin gluten",
      "Gerblé — Pan burger (hamburguesa) sin gluten, a la harina de soja",
      "Schär — Pan de molde con cereales",
      "Schär — Panecillos (Bridge Rolls) sin gluten",
      "Proceli — Pan de molde Complet",
      "Hacendado (Mercadona) — Magdalena de coco sin gluten",
    ],
  },
  {
    icon: "🍝",
    iconClass: "icon-2",
    title: "Pasta y arroz",
    text: "Pasta de maíz y arroz, fideos sin gluten y arroces certificados para todo tipo de recetas.",
    productos: [
      "Hacendado (Mercadona) — Pasta sin gluten: fusilli, espagueti, estrellas (maíz y arroz)",
      "Gallo — Pasta sin gluten (spaghetti, macarrones, tiburones)",
      "Barilla — Pasta senza glutine",
      "Schär — Pasta Anellini",
      "Carrefour Sin Gluten — Macarrones y espirales",
      "El Granero Integral — Pasta de trigo sarraceno sin gluten",
      "Hacendado (Mercadona) — Pasta rellena sin gluten (harina de arroz y maíz)",
      "Barilla — Penne Rigate sin gluten",
      "Gallo — Pasta de lentejas rojas sin gluten",
      "Schär — Pasta Fusilli sin gluten",
      "El Granero Integral — Arroz integral Bio",
    ],
  },
  {
    icon: "🍿",
    iconClass: "icon-3",
    title: "Snacks y aperitivos",
    text: "Patatas fritas certificadas, palomitas naturales y frutos secos sin trazas de gluten.",
    productos: [
      "Hacendado (Mercadona) — Patatas fritas sin gluten",
      'Carrefour — Snacks "mios!" sin gluten',
      "Lay's — Patatas fritas sin gluten",
      "Ruffles — Patatas fritas sin gluten",
      "Grefusa — Snacks sin gluten",
      "Risi — Snacks de arroz sin gluten",
      "Proceli — Picos/colines sin gluten (aceite de oliva virgen extra)",
      "Risi — Risketos, snack de maíz horneado sin gluten",
      "Risi — Palomitas de maíz sin gluten",
      "Risi — Palomitas recubiertas de chocolate sin gluten",
      "Carrefour Sin Gluten — Tortitas de maíz/arroz",
      "Carrefour Sin Gluten — Palomitas",
    ],
  },
  {
    icon: "🥣",
    iconClass: "icon-4",
    title: "Desayuno y cereales",
    text: "Avena certificada sin gluten, cereales de maíz o arroz y galletas de líneas sin gluten.",
    productos: [
      "Hacendado (Mercadona) — Corn Flakes sin gluten (Harvest Home)",
      "Hacendado (Mercadona) — Muesli crunchy chocolate sin gluten",
      "Santiveri (Noglut) — Cereales cacao y miel sin gluten",
      "Santiveri (Noglut) — Corn Flakes sin gluten",
      "Santiveri (Noglut) — Muesli frutas y frutos secos sin gluten",
      "Schär — Cereales de desayuno sin gluten",
      "Nestlé — Corn Flakes sin gluten",
      "Kellogg's — Cereales sin gluten (Dia)",
      "Go Free — Copos de maíz tostados sin gluten",
      "Gerblé — Tostadas de maíz y arroz sin gluten",
      "Gerblé — Galletas de desayuno a la harina de arroz sin gluten",
    ],
  },
  {
    icon: "🧂",
    iconClass: "icon-5",
    title: "Salsas y condimentos",
    text: "Salsa de soja sin gluten (tamari), caldos certificados y especias puras sin aditivos.",
    productos: [
      "Hacendado (Mercadona) — Salsa de soja sin gluten",
      "Hacendado (Mercadona) — Mayonesa ligera sin gluten",
      "Hacendado (Mercadona) — Kétchup sin gluten",
      "Carrefour Sin Gluten — Salsa barbacoa y salsa de soja",
      "Ybarra — Mayonesa y kétchup sin gluten",
      "Schär — Salsa boloñesa y pesto sin gluten",
      "Hellmann's — Mostaza sin gluten",
      "Hellmann's — Salsa mostaza y miel sin gluten",
      "Hellmann's — Salsa barbacoa dulce sin gluten",
      "Ybarra — Salsa miel y mostaza sin gluten",
      "Ybarra — Salsa Alioli/Gaucha sin gluten",
      "Orlando — Tomate frito sin gluten",
    ],
  },
  {
    icon: "🧊",
    iconClass: "icon-6",
    title: "Congelados",
    text: "Pizzas sin gluten, empanados de maíz y rebozados certificados listos para hornear.",
    productos: [
      "Hacendado (Mercadona) — Pizza 4 quesos sin gluten y sin lactosa",
      "Hacendado (Mercadona) — Bases de pizza sin gluten y sin lactosa",
      "Hacendado (Mercadona) — Pan rallado sin gluten",
      "Hacendado (Mercadona) — Placas de canelones/lasaña precocidas sin gluten (maíz y arroz)",
      "Frisa — Croquetas \"Caprichos de Jamón\" sin gluten (Mercadona)",
      "Carrefour Sin Gluten — Pizza congelada",
      "La Cocinera — Nuggets de pollo sin gluten (rebozados con harina de arroz y garbanzo)",
      "Hacendado (Mercadona) — San Jacobos de cerdo sin gluten",
      "Schär — Pizza congelada 4 quesos sin gluten (Alcampo)",
      "Schär — Base de pizza congelada sin gluten",
    ],
  },
  {
    icon: "🥤",
    iconClass: "icon-7",
    title: "Bebidas",
    text: "Cerveza sin gluten, horchata y batidos certificados aptos para celíacos.",
    productos: [
      "Damm — Cerveza Daura sin gluten",
      "Damm — Daura Märzen sin gluten",
      "Chufi — Horchata de chufa (naturalmente sin gluten)",
      "Hacendado (Mercadona) — Horchata de chufa sin gluten",
      "ColaCao — Cacao soluble sin gluten",
      "Puleva — Batido sin gluten",
      "Estrella Galicia — Cerveza Sin Gluten",
      "Mahou — Cerveza Sin Gluten",
      "Ambar — Especial Sin Gluten",
      "Ambar — 0,0 Sin Gluten (sin alcohol)",
      "Free Damm — Cerveza 0,0 sin gluten",
    ],
  },
  {
    icon: "🍫",
    iconClass: "icon-8",
    title: "Dulces y postres",
    text: "Chocolate sin gluten, bizcochos y turrones certificados en temporada.",
    productos: [
      "Hacendado (Mercadona) — Galletas María sin gluten y sin lactosa",
      "Hacendado (Mercadona) — Cookies con chispas de chocolate sin gluten",
      "Hacendado (Mercadona) — Bizcocho de chocolate sin gluten y sin lactosa",
      "Gullón — Galletas María sin gluten",
      "Gullón — Sharkies sin gluten (infantil)",
      "Gullón — Digestive sin gluten",
      "Proceli — Bizcochitos rellenos (Petite Fraise / Petite Délice)",
      "Gullón Diet Nature — Digestive sin azúcar, sin gluten",
      "Gerblé — Galletas con chispas de chocolate sin gluten",
      "Delaviuda — Turrón duro sin gluten",
      "Hacendado (Mercadona) — Bizcocho de limón sin gluten",
      "Valor — Chocolate negro 85% sin azúcares añadidos, sin gluten",
      "Valor — Postres de chocolate negro 70% sin gluten",
    ],
  },
  {
    icon: "🧀",
    iconClass: "icon-9",
    title: "Lácteos y alternativas",
    text: "Quesos naturales, yogures sin aditivos y bebidas vegetales (avena, soja, almendra) certificadas sin gluten.",
    productos: [
      "Hacendado (Mercadona) — Yogur natural sin gluten",
      "Hacendado (Mercadona) — Postre lácteo cremoso sin lactosa y sin gluten",
      "Hacendado (Mercadona) — Bebida de avena sin gluten",
      "Alpro — Bebida de avena sin gluten certificada",
      "Central Lechera Asturiana — Bebida de avena sin gluten",
      "Hacendado (Mercadona) — Skyr sin gluten",
      "Vivesoy — Bebida de avena sin azúcar",
      "Vivesoy — Bebida de frutos secos sin azúcar",
      "Kaiku Begetal — Bebida vegetal de avena/almendra",
      "Alpro (Danone) — Postre vegetal de coco natural",
      "Alpro (Danone) — Frutos rojos y dátiles sin azúcares añadidos",
    ],
  },
  {
    icon: "🥫",
    iconClass: "icon-10",
    title: "Legumbres y conservas",
    text: "Legumbres cocidas al natural y conservas de pescado en aceite de oliva o al natural, sin aditivos con gluten.",
    productos: [
      "Hacendado (Mercadona) — Garbanzos cocidos sin gluten",
      "Hacendado (Mercadona) — Lenteja pardina cocida sin gluten",
      "Hacendado (Mercadona) — Alubias blancas cocidas sin gluten",
      "Hacendado (Mercadona) — Atún en aceite de oliva sin gluten",
      "Litoral — Legumbres cocidas sin gluten",
      "El Granero Integral — Legumbres ecológicas sin gluten",
      "Carrefour Sin Gluten — Legumbres cocidas",
      "Luengo — Legumbres cocidas sin gluten",
      "Cidacos — Legumbres en conserva",
      "Carretilla — Fabada asturiana sin gluten",
      "Calvo — Atún claro en aceite de oliva sin gluten",
      "Isabel — Atún claro en aceite de girasol alto oleico, sin gluten y sin lactosa",
    ],
  },
  {
    icon: "🌾",
    iconClass: "icon-11",
    title: "Harinas y repostería",
    text: "Harina de arroz, maíz y almendra, y mezclas panificables certificadas para hornear en casa.",
    productos: [
      "Hacendado (Mercadona) — Preparado para panificación y repostería sin gluten",
      "Hacendado (Mercadona) — Preparado para bizcocho sin gluten",
      "Schär — Mix B Pan (harina panificable sin gluten)",
      "El Granero Integral — Harina de arroz sin gluten",
      "El Granero Integral — Harina de trigo sarraceno sin gluten",
      "Beiker — Preparado panificable sin gluten",
      "Adpan — Mix panadera sin gluten",
      "NaturGreen — Harina de trigo sarraceno Bio sin gluten",
      "NaturGreen — Harina de arroz integral Bio sin gluten",
      "NaturGreen — Harina de garbanzo Bio sin gluten",
      "NaturGreen — Harina de avena integral Bio sin gluten",
      "NaturGreen — Mezcla de harina para pan Bio sin gluten",
      "Ceresin — Preparado panificable y de repostería sin gluten",
    ],
  },
  {
    icon: "👶",
    iconClass: "icon-12",
    title: "Alimentación infantil",
    text: "Potitos, papillas y galletas de iniciación certificados sin gluten para bebés y niños.",
    productos: [
      "Nestlé — Papilla de cereales sin gluten (crema de arroz)",
      "Nestlé — Papilla maíz y arroz sin gluten",
      "Blevit (Ordesa) — Blevit Plus Bibe sin gluten (arroz y maíz)",
      "Nutribén — Papilla de cereales sin gluten",
      "Hero Baby — Papilla de cereales sin gluten",
      "Smileat — Potitos y papillas ecológicas sin gluten",
      "Hacendado (Mercadona) — Potitos de fruta (naturalmente sin gluten)",
      "Nutribén — Harina Vegetal Primera Papilla sin gluten y sin lactosa",
      "Hero Solo — Papilla de cereales sin gluten",
      "Hero Baby Pedialac — Papilla de cereales sin gluten",
      "Holle — Papilla de 3 cereales sin gluten Bio",
      "Gerber (Nestlé) — Papilla de arroz sin gluten",
    ],
  },
];

// Catálogo sin gluten por supermercado. Cada clave de "categorias" debe
// coincidir con un "title" de supermercadoCategories (se reutiliza su
// icono). Solo se listan categorías con productos verificados vía
// búsqueda web para esa cadena concreta — si una cadena no tiene una
// categoría, es porque no se encontraron datos fiables, no porque no
// venda nada sin gluten ahí.
const supermercadosCatalogo = {
  mercadona: {
    label: "Mercadona",
    categorias: {
      "Panadería y bollería": [
        "Hacendado — Pan de molde sin gluten blanco",
        "Hacendado — Pan de molde multicereales sin gluten",
        "Hacendado — Pan de molde cereales sin gluten",
        "Hacendado — Magdalenas sin gluten",
        "Hacendado — Picos sin gluten",
        "Hacendado — Tostadas sin gluten",
      ],
      "Pasta y arroz": [
        "Hacendado — Fusilli sin gluten (harina de maíz y arroz)",
        "Hacendado — Espaguetis sin gluten",
        "Hacendado — Macarrones/Coditos sin gluten",
      ],
      "Snacks y aperitivos": [
        "Hacendado — Patatas fritas 0% sal añadida sin gluten",
        "Hacendado — Patatas fritas extra crujientes",
        "Hacendado — Maíz palomitas natural para microondas",
        "Hacendado — Palomitas de maíz dulces para microondas",
        "Hacendado — Crackers sin gluten con romero",
      ],
      "Desayuno y cereales": [
        "Hacendado — Cereales rellenos de crema de cacao y avellana sin gluten",
        "Hacendado — Copos de avena sin gluten",
      ],
      "Salsas y condimentos": ["Hacendado — Salsa de soja sin gluten"],
      Congelados: [
        "Hacendado — Pizza 4 quesos sin gluten y sin lactosa (ultracongelada)",
        "Hacendado — Bases de pizza sin gluten y sin lactosa (ultracongeladas)",
        "Hacendado — Arroz tres delicias ultracongelado sin gluten",
      ],
      Bebidas: [
        "Mahou — Cerveza sin gluten 0,0% sin alcohol tostada",
        "Free Damm — Cerveza sin gluten 0,0% sin alcohol",
        "Hacendado — Bebida de avena 0% azúcar sin gluten",
      ],
      "Dulces y postres": [
        "Hacendado — Bizcocho de chocolate sin gluten",
        "Hacendado — Bizcocho de chocolate sin gluten y sin lactosa",
        "Hacendado — Turrón crema de almendras 0% azúcares añadidos sin gluten",
      ],
      "Lácteos y alternativas": [
        "Hacendado — Queso fresco batido 0% sin gluten",
        "Hacendado — Bebida de avena sin gluten",
        "Alpro — Bebida de avena/soja sin gluten",
      ],
      "Legumbres y conservas": [
        "Hacendado — Garbanzos cocidos a la jardinera sin gluten",
        "Hacendado — Fusilli de lentejas rojas (100% harina de lentejas, sin gluten)",
      ],
      "Harinas y repostería": [
        "Hacendado — Harina de maíz fina precocinada sin gluten",
        "Hacendado — Harina de garbanzo sin gluten",
        "Hacendado — Preparado para bizcocho sin gluten",
        "Hacendado — Preparado para panificación y repostería sin gluten",
      ],
      "Alimentación infantil": [
        "Hero Baby — Papilla sin gluten crema de arroz +4 meses",
        "Nestlé — Papilla maíz y arroz sin gluten +4 meses",
        "Hacendado — Potitos de fruta sin azúcares añadidos, sin gluten",
      ],
    },
  },
  carrefour: {
    label: "Carrefour",
    categorias: {
      "Panadería y bollería": [
        "Carrefour No Gluten — Pan de molde Classic sin gluten",
        "Carrefour No Gluten — Pan de molde con semillas sin gluten",
        "Carrefour No Gluten — Magdalenas redondas sin gluten y sin lactosa",
        "Carrefour No Gluten — Magdalenas valencianas sin gluten y sin lactosa",
        "Carrefour No Gluten — Croissant Classic sin gluten",
        "Carrefour No Gluten — Baguette sin gluten",
      ],
      "Pasta y arroz": [
        "Carrefour Classic No Gluten — Espaguetis de maíz y arroz",
        "Carrefour Classic No Gluten — Macarrones de maíz y arroz",
        "Carrefour Classic No Gluten — Espirales de maíz y arroz",
        "Carrefour Classic — Arroz blanco cocido sin gluten",
        "Gallo — Placas para lasaña y canelones sin gluten",
      ],
      "Snacks y aperitivos": [
        "Risi — Risketos sin gluten",
        "Risi — Triskys sin gluten",
        'Risi Mios! — Aperitivo de maíz sabor tomillo y limón sin gluten',
        "Risi Mios! — Aperitivo de maíz y chía con sal marina sin gluten",
        "Mission — Tortillas de maíz y arroz sin gluten",
      ],
      "Desayuno y cereales": [
        "Carrefour Classic — Corn flakes sin gluten y sin azúcar añadido",
        "Carrefour Sensation — Muesli crujiente sin gluten y sin azúcar añadido",
        "Nestlé — Cereales de maíz Corn Flakes sin gluten",
        "Gullón — Galletas María sin gluten y sin lactosa",
        "Gullón — Galletas Digestive sin gluten y sin lactosa",
      ],
      "Salsas y condimentos": [
        "Kikkoman — Salsa de soja sin gluten",
        "Kikkoman — Salsa de soja Tamari sin gluten",
        "Tiger Khan — Salsa de soja tradicional Gold sin gluten",
      ],
      Congelados: [
        "Carrefour Classic — Base de pizza sin gluten",
        "Pescanova — Nuggets de merluza sin gluten",
        "Pescanova — Varitas popcorn de merluza sin gluten",
        "Gallo — Placas para lasaña y canelones sin gluten",
      ],
      Bebidas: [
        "Carrefour Sensation — Cerveza artesana Radler sin gluten",
        "Carrefour Sensation — Cerveza artesana sin gluten",
      ],
      "Dulces y postres": [
        "Carrefour Sensation — Turrón blando crujiente sin gluten",
        "Carrefour Sensation — Turrón crujiente de chocolate blanco con galleta negra sin gluten",
        "Carrefour Sensation — Turrón duro sin gluten",
        "Carrefour Sensation — Turrón blando sin gluten",
        "Carrefour Sensation — Turrón praliné de pistacho sin gluten",
        "Carrefour Sensation — Turrón de guirlache sin gluten",
      ],
      "Lácteos y alternativas": [
        "Carrefour — Bebida de soja sin azúcar añadido sin gluten",
        "YoSoy — Bebida de avena sin gluten",
        "YoSoy — Bebida de avena ecológica sin gluten",
      ],
      "Legumbres y conservas": [
        "Carrefour Simply — Garbanzos cocidos",
        "Carrefour Classic — Alubias con verduras sin gluten",
        "Litoral — Fabada Asturiana sin gluten",
      ],
      "Harinas y repostería": [
        "Carrefour No Gluten — Preparado panificable Extra sin gluten y sin lactosa",
        "Carrefour No Gluten — Harina para pan y pastelería sin gluten",
        "Carrefour Classic No Gluten — Preparado para bizcocho sin gluten",
      ],
      "Alimentación infantil": [
        "Carrefour Baby Bio — Papilla infantil con cereales desde 4 meses, ecológica, sin gluten",
      ],
    },
  },
  lidl: {
    label: "Lidl",
    categorias: {
      "Panadería y bollería": [
        "La Cestera — Pan de molde sin gluten",
        "La Cestera — Magdalenas sin gluten",
        "La Cestera — Bizcocho de chocolate sin gluten",
        "La Cestera — Palitos sin gluten",
      ],
      "Pasta y arroz": [
        "Combino — Penne sin gluten (maíz y arroz)",
        "Vitasia — Fideos de arroz",
        "Vitasia — Noodles de konjac sin gluten",
      ],
      "Snacks y aperitivos": [
        "Snack Day — Patatas fritas sin gluten con aceite de oliva",
        "Sondey — Tortitas de maíz sin gluten",
        "Alesto — Frutos secos naturales",
      ],
      Congelados: [
        "Lidl — Nuggets de pollo sin gluten y sin lactosa",
        "Dr. Oetker Ristorante — Pizza Prosciutto sin gluten y sin lactosa",
      ],
      "Dulces y postres": [
        "Sondey — Cookies de chocolate sin gluten (veganas)",
        "Sondey — Galletas María sin gluten",
        "Gelatelli — Helados sin gluten",
      ],
      "Harinas y repostería": [
        "Belbake — Harina/preparado sin gluten para pan y pizza",
        "Belbake — Preparado panificable sin gluten (pan blanco)",
      ],
    },
  },
  dia: {
    label: "Dia",
    categorias: {
      "Panadería y bollería": [
        "El Molino de Dia — Magdalenas sin gluten (también sin lactosa)",
        "Panceliac (Dia) — Picos sin gluten",
        "Panceliac (Dia) — Pan rallado sin gluten",
        "Panceliac (Dia) — Pan de molde sin gluten",
        "Dia Sin Gluten — Pan de molde y panecillos de hamburguesa sin gluten",
      ],
      "Pasta y arroz": [
        "Gallo (Dia) — Espaguetis sin gluten",
        "Gallo (Dia) — Macarrones sin gluten",
        "Dia Sin Gluten — Pasta sin gluten (gama propia)",
      ],
      "Snacks y aperitivos": [
        "Snack Maniac (Dia) — Patatas fritas gourmet extra crujientes sin gluten",
        "Snack Maniac (Dia) — Patatas fritas campesinas sin gluten",
        "Snack Maniac (Dia) — Torzitos sabor queso sin gluten",
        "Snack Maniac (Dia) — Nachos sabor queso tex-mex sin gluten",
        "Tosfrit (Dia) — Aros de maíz frito sin gluten",
      ],
      "Desayuno y cereales": [
        "Nestlé (Dia) — Corn Flakes sin gluten",
        "Dia Sin Gluten — Cereales sin gluten (gama propia)",
      ],
      "Salsas y condimentos": [
        "Dia Selección Mundial — Salsa de soja sin gluten",
        "Dia Salseo — Ketchup sin gluten",
        "Dia Salseo — Mayonesa sin gluten y sin lactosa",
      ],
      Congelados: [
        "Dia Al Punto — Lasaña boloñesa sin gluten",
        "Dr. Oetker Ristorante (Dia) — Pizza prosciutto sin gluten",
        "Dia Sin Gluten — Empanadillas sin gluten",
      ],
      Bebidas: [
        "Dia Ramblers — Cerveza especial sin gluten",
        "Dia — Horchata sin gluten",
        "Dia (Vegedia) — Bebida de chufa 0% azúcares, sin gluten y sin lactosa",
      ],
      "Dulces y postres": [
        "Dulce Noel Dia — Turrón crujiente de chocolate sin azúcares añadidos, sin gluten",
        "Dulce Noel Dia — Turrón de chocolate con leche y almendras sin gluten",
        "Dulce Noel Dia — Turrón de chocolate con leche crujiente clásico, sin gluten",
        "Galleteca (Dia Sin Gluten) — Galletas con pepitas de chocolate y sabor mantequilla, sin gluten",
      ],
      "Lácteos y alternativas": [
        "Dia — Bífidus con piña y coco doble 0%, sin gluten",
        "Dia — Bífidus con nueces y cereales doble 0%, sin gluten",
        "Dia — Bífidus con fresa doble 0%, sin gluten",
        "Dia Láctea — Yogur sabor fresa sin gluten",
      ],
      "Legumbres y conservas": [
        "Dia — Lentejas cocidas sin gluten",
        "Dia — Garbanzos cocidos sin gluten",
        "Dia — Alubias blancas extra sin gluten",
        "Dia — Lentejas con chorizo sin gluten",
        "Vegecampo de Dia — Lentejas pardinas sin gluten",
      ],
      "Harinas y repostería": [
        "El Molino de Dia — Harina de garbanzo sin gluten",
        "Dia Delimagic — Preparado para hornear en polvo sin gluten",
      ],
      "Alimentación infantil": [
        "Hero Baby (Dia) — Potitos de frutas ecológicos sin gluten",
        "Nestlé (Dia) — Puré de 7 frutas sin gluten",
        "Smileat / Be Plus (Dia) — Potitos y tarritos sin gluten, sin lactosa",
      ],
    },
  },
  aldi: {
    label: "Aldi",
    categorias: {
      "Panadería y bollería": [
        "Aldi — Pan de molde sin gluten",
        "GutBio — Pan sin gluten (base teff)",
        "Aldi — Bagels sin gluten",
        "Aldi — Panecillos sin gluten",
      ],
      "Pasta y arroz": [
        "GutBio — Fusilli de arroz integral y teff",
        "GutBio — Pasta de lentejas",
        "GutBio — Pasta de legumbres variadas",
        "GutBio — Espaguetis de edamame ecológicos",
      ],
      "Snacks y aperitivos": [
        "Aldi — Patatas fritas sin gluten sabor entrecot con setas",
        "Aldi — Patatas fritas sin gluten sabor sobrasada ibérica",
        "AURADA — Tortitas de maíz",
        "AURADA — Tortitas de arroz",
        "AURADA — Tortitas de maíz con chocolate negro",
      ],
      "Desayuno y cereales": [
        "Golden Bridge — Copos de avena integral certificados sin gluten",
        "Golden Bridge — Copos de avena integral XXL",
        "Golden Bridge — Avena Rings",
      ],
      "Salsas y condimentos": ["La Villa — Kétchup sin gluten", "La Villa — Mayonesa sin gluten"],
      Congelados: [
        "Aldi — Pizza de jamón y queso sin gluten",
        "Aldi — Gama de pizzas sin gluten (16 referencias)",
        "Aldi — Empanadillas sin gluten",
        "Aldi — Chicken fingers / croquetas de pollo empanadas sin gluten",
      ],
      Bebidas: [
        "Karlsquell — Cerveza Especial Sin Gluten (Bio)",
        "Maternus — Cerveza Rubia Sin Gluten",
        "Milsani — Horchata sin gluten",
      ],
      "Dulces y postres": [
        "Biscotto — Galletas Chocobrownie sin gluten",
        "Biscotto — Galletas con pepitas de chocolate sin gluten",
        "GutBio — Galletas de avena sin gluten sabor limón y canela",
        "GutBio — Galletas de avena sin gluten sabor naranja, cúrcuma y jengibre",
        "Choceur — Bombones de chocolate sin gluten",
        "Flor de Navidad — Turrón sin gluten (blando Jijona y yema tostada)",
      ],
      "Lácteos y alternativas": [
        "GutBio — Bebida de avena ecológica sin gluten",
        "GutBio — Bebida de soja ecológica sin gluten",
        "GutBio — Bebida de arroz ecológica sin gluten",
        "GutBio — Bebida de almendra sin gluten",
      ],
      "Legumbres y conservas": [
        "GutBio — Garbanzos y alubias extra cocidos ecológicos",
        "GutBio — Lentejas y alubias rojas extra cocidas ecológicas",
        "GutBio — Plato de alubias, lentejas con verduras y garbanzos con espinacas",
      ],
      "Harinas y repostería": [
        "Aldi — Preparado para pan sin gluten (mezcla + levadura)",
        "Aldi — Harina de arroz sin gluten",
        "Aldi — Levadura de panadería/repostería sin gluten",
      ],
    },
  },
  consum: {
    label: "Consum",
    categorias: {
      "Panadería y bollería": [
        "Consum — Hogaza sin gluten",
        "Consum — Baguette sin gluten",
        "Consum — Baguettina sin gluten (congelada)",
        "Consum — Tostadas sin gluten integrales",
        "Consum — Pan de molde sin gluten cereales y semillas",
      ],
      "Pasta y arroz": ["Consum — Spaghetti sin gluten", "Consum — Fideos sin gluten", "Consum — Tallarines de arroz"],
      "Snacks y aperitivos": [
        "Consum — Tortitas de maíz sin gluten",
        "Consum — Tortillas de maíz sin gluten",
        "Consum — Crackers sin gluten",
      ],
      "Desayuno y cereales": [
        "Consum — Cereales Choco Zero sin gluten y sin azúcares",
        "Consum — Cereales rellenos de leche sin gluten",
        "Consum — Cereales rellenos de choco sin gluten",
        "Consum — Corn Flakes Classic sin azúcar y sin gluten",
        "Consum — Arroz inflado choco sin gluten",
      ],
      "Salsas y condimentos": ["Consum — Tomate frito sin gluten", "Consum — Salsa de soja baja en sal y sin gluten"],
      Congelados: [
        "Ristorante (Dr. Oetker, en Consum) — Pizza Mozzarella sin gluten",
        "Ristorante — Pizza Prosciutto sin gluten y sin lactosa",
        "Ristorante — Pizza Jamón y Queso sin gluten y sin lactosa",
        "Consum — Nuggets de pollo sin gluten y sin lactosa",
        "Consum — Base de pizza sin gluten",
        "Consum — Cono nata-chocolate x4 sin gluten y sin lactosa",
      ],
      Bebidas: [
        "Consum — Cerveza sin gluten",
        "Damm — Daura, cerveza sin gluten",
        "Consum — Cerveza Celíacos (0,0)",
      ],
      "Dulces y postres": [
        "Consum — Magdalenas artesanas sin gluten",
        "Consum — Plumcake sin gluten con pepitas de chocolate",
        "Consum — Muffin de chocolate sin gluten",
        "Consum — Bizcocho sin gluten con pepitas de chocolate",
        "Consum — Galleta María sin gluten",
        "Consum — Bombones surtidos sin gluten",
      ],
      "Lácteos y alternativas": [
        "Consum — Queso Pell Florida de leche de cabra pasteurizada, sin gluten",
        "Consum — Queso fresco Servilleta de leche de vaca pasteurizada, sin gluten",
        "Consum — Queso de oveja pasta blanda, sin gluten",
      ],
      "Harinas y repostería": ["Consum — Harina mix sin gluten multiusos", "Consum — Pan rallado sin gluten"],
      "Alimentación infantil": ["Consum — Crema de arroz sin gluten (papilla)", "Consum — Crema de arroz sin gluten y sin azúcar (papilla)"],
    },
  },
};

const recetas = [
  {
    icon: "🍳",
    title: "Tortilla de patatas clásica",
    meta: "~320 kcal · 35 min",
    ingredientes: ["4 patatas medianas", "5 huevos", "1 cebolla", "Aceite de oliva virgen extra", "Sal"],
    pasos: [
      "Pelar las patatas y cortarlas en láminas finas (2-3 mm); cortar la cebolla en juliana fina.",
      "Calentar abundante aceite de oliva en una sartén amplia a fuego medio-bajo.",
      "Añadir las patatas y la cebolla, salar ligeramente y confitar 20-25 minutos, removiendo de vez en cuando, hasta que estén blandas sin dorarse.",
      "Escurrir bien el aceite con un colador, reservando un par de cucharadas para cuajar.",
      "Batir los huevos en un bol amplio, mezclar con las patatas y la cebolla templadas y dejar reposar 5 minutos.",
      "Calentar el aceite reservado en una sartén antiadherente de 20-22 cm y verter la mezcla, repartiendo bien.",
      "Cuajar a fuego medio 2-3 minutos, dar la vuelta con ayuda de un plato y cuajar otros 2-3 minutos por el otro lado.",
      "Dejar reposar unos minutos antes de cortar y servir.",
    ],
  },
  {
    icon: "🍗",
    title: "Pollo al horno con verduras",
    meta: "~410 kcal · 45 min",
    ingredientes: ["4 muslos de pollo", "1 calabacín", "1 pimiento rojo", "2 patatas", "Aceite de oliva y romero"],
    pasos: [
      "Precalentar el horno a 200 °C con calor arriba y abajo.",
      "Lavar y cortar el calabacín, el pimiento y las patatas en trozos regulares de tamaño similar.",
      "Salpimentar los muslos de pollo y las verduras.",
      "Colocar todo en una bandeja de horno amplia, sin amontonar, para que se doren en vez de cocerse al vapor.",
      "Regar con un buen chorro de aceite de oliva y espolvorear el romero.",
      "Hornear 25 minutos, sacar y dar la vuelta al pollo, removiendo las verduras.",
      "Hornear 15-20 minutos más, hasta que el pollo esté dorado y las verduras tiernas.",
      "Dejar reposar 5 minutos fuera del horno antes de servir.",
    ],
  },
  {
    icon: "🍤",
    title: "Arroz con verduras y gambas",
    meta: "~380 kcal · 30 min",
    ingredientes: ["300 g de arroz", "200 g de gambas peladas", "1 pimiento verde", "Guisantes", "Caldo de verduras sin gluten"],
    pasos: [
      "Picar el ajo y el pimiento verde en trozos pequeños.",
      "Calentar aceite de oliva en una cazuela ancha y sofreír el ajo y el pimiento 4-5 minutos, hasta que estén blandos.",
      "Añadir el arroz y remover 1-2 minutos para que se impregne del sofrito.",
      "Verter el caldo de verduras caliente (el doble de volumen que el arroz) y llevar a ebullición.",
      "Bajar el fuego a medio-bajo, añadir los guisantes y cocer 15 minutos sin remover demasiado.",
      "Incorporar las gambas peladas y cocer 3 minutos más, hasta que cambien de color.",
      "Apagar el fuego, tapar y dejar reposar 2-3 minutos antes de servir.",
    ],
  },
  {
    icon: "🥑",
    title: "Ensalada de quinoa y aguacate",
    meta: "~340 kcal · 20 min",
    ingredientes: ["150 g de quinoa", "1 aguacate", "Tomates cherry", "Pepino", "Limón y aceite de oliva"],
    pasos: [
      "Enjuagar la quinoa con un colador fino bajo el grifo para quitar el sabor amargo de la saponina.",
      "Cocerla en agua con una pizca de sal (1 parte de quinoa por 2 de agua) 12-15 minutos, hasta que los granos se abran.",
      "Escurrir y dejar enfriar completamente extendida en una bandeja, para que no quede pastosa.",
      "Cortar el aguacate en dados, los tomates cherry por la mitad y el pepino en cubos pequeños.",
      "Mezclar la quinoa fría con las verduras en un bol grande.",
      "Preparar la vinagreta batiendo el zumo de limón, el aceite de oliva y una pizca de sal.",
      "Aliñar justo antes de servir para que el aguacate no se oxide.",
    ],
  },
  {
    icon: "🎃",
    title: "Crema de calabaza",
    meta: "~210 kcal · 30 min",
    ingredientes: ["500 g de calabaza", "1 cebolla", "1 zanahoria", "Caldo de verduras sin gluten", "Un chorrito de nata ligera (opcional)"],
    pasos: [
      "Pelar y trocear la calabaza, la cebolla y la zanahoria en trozos medianos.",
      "Calentar un chorro de aceite de oliva en una olla y pochar la cebolla y la zanahoria a fuego medio-bajo 8-10 minutos.",
      "Añadir la calabaza troceada y rehogar 2-3 minutos más.",
      "Cubrir con el caldo de verduras caliente (que cubra ligeramente las verduras) y salar.",
      "Cocer a fuego medio 20-25 minutos, hasta que todo esté muy tierno al pincharlo con un tenedor.",
      "Triturar con batidora hasta conseguir una crema fina, añadiendo más caldo si queda demasiado espesa.",
      "Añadir un chorrito de nata ligera si se desea, remover y servir bien caliente.",
    ],
  },
  {
    icon: "🐟",
    title: "Salmón a la plancha con puré de boniato",
    meta: "~430 kcal · 30 min",
    ingredientes: ["2 lomos de salmón", "2 boniatos", "Leche o bebida vegetal", "Aceite de oliva", "Eneldo"],
    pasos: [
      "Pelar los boniatos y cortarlos en trozos medianos.",
      "Cocerlos en agua con sal 15-18 minutos, hasta que estén muy tiernos al pincharlos.",
      "Escurrir y triturar con un poco de leche caliente y un chorrito de aceite hasta obtener un puré fino; salpimentar.",
      "Secar bien los lomos de salmón con papel de cocina y salpimentar.",
      "Calentar una plancha o sartén antiadherente con un poco de aceite a fuego fuerte.",
      "Marcar el salmón por el lado de la piel 3-4 minutos, hasta que esté crujiente, y dar la vuelta.",
      "Cocinar 2-3 minutos más por el otro lado, según el grosor, hasta que quede jugoso por dentro.",
      "Servir el salmón sobre una base de puré de boniato y espolvorear eneldo fresco picado.",
    ],
  },
  {
    icon: "🍅",
    title: "Gazpacho andaluz",
    meta: "~150 kcal · 15 min",
    ingredientes: ["1 kg de tomates maduros", "1 pepino", "1 pimiento verde", "1 diente de ajo", "Aceite de oliva, vinagre y sal"],
    pasos: [
      "Lavar los tomates y quitarles el pedúnculo; trocear junto con el pepino, el pimiento verde y el ajo.",
      "Colocar todas las verduras en el vaso de la batidora junto con el aceite de oliva, el vinagre y la sal.",
      "Triturar a máxima potencia 2-3 minutos, hasta obtener una mezcla completamente fina.",
      "Probar y rectificar de sal, vinagre o aceite al gusto.",
      "Colar con un colador fino o chino si se prefiere una textura sin pieles ni pepitas.",
      "Enfriar en la nevera un mínimo de 1-2 horas antes de servir bien frío.",
      "Servir con dados de pepino, pimiento y tomate picado por encima si se desea.",
    ],
  },
  {
    icon: "🍖",
    title: "Albóndigas en salsa de tomate",
    meta: "~450 kcal · 50 min",
    ingredientes: ["500 g de carne picada", "1 huevo", "Pan rallado sin gluten", "Tomate triturado", "Ajo, perejil y aceite de oliva"],
    pasos: [
      "Picar finamente el ajo y el perejil.",
      "En un bol grande, mezclar la carne picada con el huevo, el pan rallado sin gluten, el ajo y el perejil; salpimentar y amasar bien.",
      "Dejar reposar la masa 10 minutos en la nevera para que sea más fácil de formar.",
      "Formar bolas de tamaño similar con las manos humedecidas.",
      "Calentar aceite de oliva en una sartén y dorar las albóndigas por todos los lados a fuego medio-alto.",
      "Retirar y reservar; en la misma sartén, añadir el tomate triturado y una pizca de sal.",
      "Incorporar de nuevo las albóndigas a la salsa y cocer a fuego lento 20-25 minutos, removiendo de vez en cuando.",
      "Servir calientes, con un poco de perejil picado por encima.",
    ],
  },
  {
    icon: "🥙",
    title: "Poke bowl de atún",
    meta: "~420 kcal · 25 min",
    ingredientes: ["200 g de atún fresco", "Arroz cocido", "Edamame", "Aguacate y zanahoria", "Salsa de soja sin gluten (tamari)"],
    pasos: [
      "Cortar el atún fresco en dados de 1-2 cm.",
      "Marinar el atún con la salsa de soja sin gluten (tamari) durante 10-15 minutos en la nevera.",
      "Cocer el arroz según las instrucciones del paquete y dejar enfriar ligeramente (templado, no caliente).",
      "Cortar el aguacate en láminas y la zanahoria en tiras finas o rallada.",
      "Descongelar o cocer el edamame según indique el envase.",
      "Montar el bowl colocando el arroz como base y distribuyendo el atún, el aguacate, la zanahoria y el edamame en secciones.",
      "Terminar con un poco de la marinada de tamari por encima y semillas de sésamo si se desea.",
    ],
  },
  {
    icon: "🥞",
    title: "Crepes de trigo sarraceno con fruta",
    meta: "~280 kcal · 20 min",
    ingredientes: [
      "150 g de harina de trigo sarraceno (naturalmente sin gluten)",
      "2 huevos",
      "250 ml de leche o bebida vegetal",
      "Fruta fresca al gusto",
      "Una pizca de sal",
    ],
    pasos: [
      "Tamizar la harina de trigo sarraceno en un bol grande para evitar grumos.",
      "Batir los huevos aparte y añadirlos a la harina poco a poco, alternando con la leche, hasta conseguir una masa homogénea.",
      "Añadir una pizca de sal y dejar reposar la masa 15-20 minutos a temperatura ambiente.",
      "Calentar una sartén antiadherente a fuego medio y engrasar ligeramente con un poco de aceite.",
      "Verter un cucharón de masa y repartir girando la sartén para que quede una capa fina y uniforme.",
      "Cocinar 1-2 minutos hasta que los bordes se despeguen, dar la vuelta y cocinar 1 minuto más por el otro lado.",
      "Repetir con el resto de la masa, apilando los crepes en un plato.",
      "Rellenar o cubrir con fruta fresca troceada al gusto y servir templados.",
    ],
  },
  {
    icon: "🥣",
    title: "Porridge de avena con frutos rojos",
    meta: "~320 kcal · 10 min",
    ingredientes: [
      "80 g de copos de avena certificados sin gluten",
      "250 ml de leche o bebida vegetal",
      "Un puñado de frutos rojos (fresas, arándanos, frambuesas)",
      "1 cucharadita de miel",
      "Canela al gusto",
    ],
    pasos: [
      "Verter la avena y la leche en un cazo pequeño.",
      "Calentar a fuego medio, removiendo con frecuencia para que no se pegue.",
      "Cocer 5-7 minutos, hasta que la avena haya absorbido el líquido y tenga una textura cremosa.",
      "Retirar del fuego y dejar templar 1-2 minutos.",
      "Servir en un bol, añadir los frutos rojos por encima, un chorrito de miel y espolvorear canela.",
    ],
  },
  {
    icon: "🥔",
    title: "Vichyssoise (crema fría de puerro y patata)",
    meta: "~230 kcal · 40 min + enfriado",
    ingredientes: ["3 puerros (solo la parte blanca)", "2 patatas medianas", "1 cebolla pequeña", "Caldo de verduras sin gluten", "Nata líquida o bebida vegetal"],
    pasos: [
      "Lavar bien los puerros entre las capas y cortarlos en rodajas finas, junto con la cebolla.",
      "Pelar y trocear las patatas en dados medianos.",
      "Calentar un chorro de aceite de oliva en una olla y pochar el puerro y la cebolla a fuego bajo 10 minutos, sin que cojan color.",
      "Añadir las patatas y el caldo de verduras (que cubra los ingredientes) y salar.",
      "Cocer a fuego medio 20-25 minutos, hasta que la patata esté muy tierna.",
      "Triturar todo hasta obtener una crema fina; añadir un chorro de nata o bebida vegetal y volver a triturar.",
      "Dejar enfriar a temperatura ambiente y luego refrigerar al menos 2 horas.",
      "Servir bien fría, con cebollino picado por encima si se desea.",
    ],
  },
  {
    icon: "🍖",
    title: "Solomillo de cerdo con salsa de mostaza",
    meta: "~410 kcal · 35 min",
    ingredientes: ["1 solomillo de cerdo (~500 g)", "2 cucharadas de mostaza sin gluten", "200 ml de nata para cocinar", "1 cebolla", "Aceite de oliva"],
    pasos: [
      "Salpimentar el solomillo y cortarlo en medallones de 2-3 cm.",
      "Picar la cebolla finamente.",
      "Calentar aceite de oliva en una sartén a fuego fuerte y dorar los medallones 2 minutos por cada lado; retirar y reservar.",
      "En la misma sartén, bajar el fuego y pochar la cebolla 5-6 minutos, hasta que esté transparente.",
      "Añadir la nata y la mostaza, remover bien y cocinar 3-4 minutos a fuego medio hasta que espese ligeramente.",
      "Incorporar de nuevo los medallones a la salsa y cocinar 4-5 minutos más, hasta que estén hechos por dentro.",
      "Probar y rectificar de sal si es necesario.",
      "Servir caliente con la salsa por encima.",
    ],
  },
  {
    icon: "🐠",
    title: "Merluza en salsa verde",
    meta: "~280 kcal · 30 min",
    ingredientes: ["4 lomos de merluza", "3 dientes de ajo", "Perejil fresco", "200 ml de caldo de pescado sin gluten", "Aceite de oliva y 1 cucharada de harina de arroz (opcional)"],
    pasos: [
      "Salar los lomos de merluza y reservar.",
      "Picar el ajo y el perejil finamente.",
      "Calentar aceite de oliva en una cazuela amplia y dorar el ajo a fuego bajo, sin que se queme.",
      "Si se desea espesar la salsa, añadir la harina de arroz y remover 1 minuto.",
      "Verter el caldo de pescado poco a poco, removiendo para que no se formen grumos.",
      "Añadir el perejil picado y llevar a un ligero hervor.",
      "Colocar los lomos de merluza en la cazuela, con la piel hacia abajo, y cocinar a fuego medio-bajo 8-10 minutos, moviendo la cazuela de vez en cuando en vez de remover.",
      "Servir la merluza con la salsa verde por encima.",
    ],
  },
  {
    icon: "🍛",
    title: "Curry de garbanzos y espinacas",
    meta: "~360 kcal · 30 min",
    ingredientes: ["400 g de garbanzos cocidos sin gluten", "200 g de espinacas frescas", "1 cebolla", "400 ml de leche de coco", "2 cucharaditas de curry en polvo sin gluten", "1 diente de ajo"],
    pasos: [
      "Picar la cebolla y el ajo finamente.",
      "Calentar aceite de oliva en una sartén honda y sofreír la cebolla y el ajo a fuego medio 5 minutos.",
      "Añadir el curry en polvo y remover 1 minuto para que suelte aroma.",
      "Incorporar los garbanzos escurridos y remover para que se impregnen de las especias.",
      "Verter la leche de coco y cocinar a fuego medio 10-12 minutos, removiendo de vez en cuando.",
      "Añadir las espinacas y cocinar 2-3 minutos más, hasta que se ablanden.",
      "Salpimentar al gusto y servir caliente, con arroz basmati como acompañamiento si se desea.",
    ],
  },
  {
    icon: "🍝",
    title: "Carbonara sin gluten",
    meta: "~520 kcal · 20 min",
    ingredientes: ["350 g de pasta sin gluten (espagueti)", "150 g de panceta o bacon", "3 huevos", "50 g de queso parmesano rallado", "Pimienta negra"],
    pasos: [
      "Poner una olla grande con agua y sal a hervir para la pasta.",
      "Cortar la panceta en tiras o dados pequeños.",
      "Cocer la pasta sin gluten según las instrucciones del paquete (suele necesitar 1-2 minutos menos que la pasta normal).",
      "Mientras tanto, dorar la panceta en una sartén grande a fuego medio, sin aceite adicional, hasta que esté crujiente.",
      "En un bol, batir los huevos con el queso parmesano y una buena cantidad de pimienta negra molida.",
      "Escurrir la pasta reservando un cazo del agua de cocción.",
      "Añadir la pasta caliente a la sartén con la panceta y retirar del fuego.",
      "Incorporar la mezcla de huevo y queso, removiendo rápido sin volver a poner al fuego directo.",
      "Añadir un poco del agua de cocción reservada si queda demasiado espesa, y servir inmediatamente.",
    ],
  },
  {
    icon: "🍫",
    title: "Brownie sin gluten",
    meta: "~290 kcal por ración · 40 min",
    ingredientes: ["200 g de chocolate negro sin gluten", "150 g de mantequilla", "3 huevos", "180 g de azúcar", "80 g de harina de arroz o mezcla panificable sin gluten", "Nueces troceadas (opcional)"],
    pasos: [
      "Precalentar el horno a 180 °C y forrar un molde rectangular con papel de horno.",
      "Trocear el chocolate y derretirlo junto con la mantequilla al baño maría o en el microondas en golpes cortos.",
      "Dejar templar la mezcla de chocolate unos minutos.",
      "Batir los huevos con el azúcar hasta que blanqueen y dupliquen su volumen.",
      "Incorporar el chocolate derretido a los huevos, mezclando con movimientos envolventes.",
      "Tamizar la harina sin gluten sobre la mezcla y añadir con cuidado, sin batir en exceso.",
      "Añadir las nueces si se desea y verter la masa en el molde.",
      "Hornear 20-25 minutos: el interior debe quedar húmedo y ligeramente poco hecho.",
      "Dejar enfriar completamente en el molde antes de cortar en cuadrados.",
    ],
  },
];

const dietas = [
  {
    icon: "🥗",
    title: "Mediterráneo ligero",
    meta: "~1.550 kcal aprox. · pescado, quinoa, verduras",
    comidas: [
      { label: "Desayuno", text: "Yogur natural sin gluten con avena certificada y arándanos (~280 kcal)." },
      { label: "Media mañana", text: "Un puñado de nueces y una manzana (~180 kcal)." },
      { label: "Comida", text: "Pescado blanco al horno con quinoa y verduras salteadas (~480 kcal)." },
      { label: "Merienda", text: "Hummus con bastones de zanahoria y pepino (~150 kcal)." },
      { label: "Cena", text: "Ensalada de tomate, aguacate y atún con aceite de oliva (~460 kcal)." },
    ],
  },
  {
    icon: "💪",
    title: "Alto en proteína",
    meta: "~1.600 kcal aprox. · pollo, salmón, requesón",
    comidas: [
      { label: "Desayuno", text: "Tortilla de 2 huevos con espinacas y pan sin gluten tostado (~350 kcal)." },
      { label: "Media mañana", text: "Requesón con nueces (~180 kcal)." },
      { label: "Comida", text: "Pechuga de pollo a la plancha con arroz integral y brócoli (~480 kcal)." },
      { label: "Merienda", text: "Batido de proteína con leche y plátano (~200 kcal)." },
      { label: "Cena", text: "Salmón al horno con espárragos trigueros (~390 kcal)." },
    ],
  },
  {
    icon: "🥩",
    title: "Bajo en carbohidratos",
    meta: "~1.450 kcal aprox. · huevo, solomillo, ensaladas",
    comidas: [
      { label: "Desayuno", text: "Huevos revueltos con aguacate (~320 kcal)." },
      { label: "Media mañana", text: "Queso curado en lonchas y aceitunas (~150 kcal)." },
      { label: "Comida", text: "Solomillo de cerdo con ensalada verde y aceite de oliva (~420 kcal)." },
      { label: "Merienda", text: "Yogur natural sin azúcar con un puñado de almendras (~180 kcal)." },
      { label: "Cena", text: "Ensalada de pollo, rúcula, tomate y queso feta (~380 kcal)." },
    ],
  },
  {
    icon: "🌱",
    title: "Vegetariano equilibrado",
    meta: "~1.500 kcal aprox. · lentejas, tofu, avena certificada",
    comidas: [
      { label: "Desayuno", text: "Porridge de avena certificada sin gluten con bebida vegetal y fresas (~300 kcal)." },
      { label: "Media mañana", text: "Hummus con tortitas de maíz (~170 kcal)." },
      { label: "Comida", text: "Lentejas estofadas con verduras y arroz (~430 kcal)." },
      { label: "Merienda", text: "Batido de tofu con frutos rojos (~180 kcal)." },
      { label: "Cena", text: "Tofu salteado con verduras y quinoa (~420 kcal)." },
    ],
  },
];

const dietasMusculo = [
  {
    icon: "🏋️",
    title: "Volumen limpio",
    meta: "~2.400 kcal aprox. · pollo, arroz, huevo",
    comidas: [
      { label: "Desayuno", text: "Tortilla de 3 huevos con avena certificada y plátano (~450 kcal)." },
      { label: "Media mañana", text: "Batido de proteína con leche y avena certificada (~350 kcal)." },
      { label: "Comida", text: "Pechuga de pollo con arroz basmati y verduras salteadas (~650 kcal)." },
      { label: "Merienda", text: "Yogur griego con nueces y miel (~300 kcal)." },
      { label: "Cena", text: "Pollo al horno con boniato y ensalada (~650 kcal)." },
    ],
  },
  {
    icon: "🥩",
    title: "Alto calórico",
    meta: "~2.700 kcal aprox. · ternera, pasta sin gluten, frutos secos",
    comidas: [
      { label: "Desayuno", text: "Porridge de avena certificada con leche entera, plátano y almendras (~550 kcal)." },
      { label: "Media mañana", text: "Batido de proteína con crema de cacahuete y leche (~450 kcal)." },
      { label: "Comida", text: "Solomillo de ternera con pasta sin gluten y salsa de tomate (~700 kcal)." },
      { label: "Merienda", text: "Puñado de frutos secos y queso curado (~400 kcal)." },
      { label: "Cena", text: "Ternera picada con arroz y verduras al wok (~600 kcal)." },
    ],
  },
  {
    icon: "🌱",
    title: "Vegetariano proteico",
    meta: "~2.300 kcal aprox. · tofu, legumbres, quinoa",
    comidas: [
      { label: "Desayuno", text: "Porridge de avena certificada con bebida de soja y frutos rojos (~450 kcal)." },
      { label: "Media mañana", text: "Batido de proteína vegetal con plátano (~300 kcal)." },
      { label: "Comida", text: "Tofu salteado con quinoa y verduras (~600 kcal)." },
      { label: "Merienda", text: "Hummus con tortitas de maíz y frutos secos (~350 kcal)." },
      { label: "Cena", text: "Lentejas estofadas con arroz y aguacate (~600 kcal)." },
    ],
  },
  {
    icon: "💥",
    title: "Post-entreno intenso",
    meta: "~2.500 kcal aprox. · salmón, boniato, batido de proteína",
    comidas: [
      { label: "Desayuno", text: "Huevos revueltos con pan sin gluten y aguacate (~450 kcal)." },
      { label: "Media mañana", text: "Batido de proteína con avena certificada y plátano (~400 kcal)." },
      { label: "Comida", text: "Salmón al horno con boniato y brócoli (~650 kcal)." },
      { label: "Merienda", text: "Yogur griego con nueces (~300 kcal)." },
      { label: "Cena", text: "Pechuga de pavo con arroz y verduras (~700 kcal)." },
    ],
  },
];

const dietasMantenimiento = [
  {
    icon: "⚖️",
    title: "Equilibrio diario",
    meta: "~2.000 kcal aprox. · variado y equilibrado",
    comidas: [
      { label: "Desayuno", text: "Tostadas de pan sin gluten con aguacate y huevo poché (~420 kcal)." },
      { label: "Media mañana", text: "Una pieza de fruta y un puñado de almendras (~200 kcal)." },
      { label: "Comida", text: "Arroz con pollo y verduras variadas (~550 kcal)." },
      { label: "Merienda", text: "Yogur natural con granola sin gluten (~250 kcal)." },
      { label: "Cena", text: "Pescado a la plancha con patata asada y ensalada (~580 kcal)." },
    ],
  },
  {
    icon: "⚡",
    title: "Energía activa",
    meta: "~2.100 kcal aprox. · pensado para quien entrena",
    comidas: [
      { label: "Desayuno", text: "Porridge de avena certificada con plátano y miel (~450 kcal)." },
      { label: "Media mañana", text: "Batido de frutas con leche (~250 kcal)." },
      { label: "Comida", text: "Pasta sin gluten con pollo y verduras salteadas (~600 kcal)." },
      { label: "Merienda", text: "Barrita energética casera de frutos secos y dátiles (~250 kcal)." },
      { label: "Cena", text: "Tortilla de patatas con ensalada (~550 kcal)." },
    ],
  },
];

const dietasDigestion = [
  {
    icon: "🍵",
    title: "Intestino en calma",
    meta: "~1.600 kcal aprox. · suave y fácil de digerir",
    comidas: [
      { label: "Desayuno", text: "Yogur natural sin lactosa con plátano maduro (~250 kcal)." },
      { label: "Media mañana", text: "Infusión de manzanilla con compota de manzana (~120 kcal)." },
      { label: "Comida", text: "Arroz blanco con pechuga de pollo hervida y zanahoria cocida (~450 kcal)." },
      { label: "Merienda", text: "Puré de pera (~150 kcal)." },
      { label: "Cena", text: "Pescado blanco al vapor con calabacín cocido (~430 kcal)." },
    ],
  },
  {
    icon: "🌿",
    title: "Antiinflamatorio",
    meta: "~1.700 kcal aprox. · cúrcuma, jengibre, omega-3",
    comidas: [
      { label: "Desayuno", text: "Porridge de avena certificada con cúrcuma, canela y arándanos (~350 kcal)." },
      { label: "Media mañana", text: "Nueces y una naranja (~200 kcal)." },
      { label: "Comida", text: "Salmón al horno con boniato y brócoli al vapor (~500 kcal)." },
      { label: "Merienda", text: "Infusión de jengibre con un puñado de frutos rojos (~150 kcal)." },
      { label: "Cena", text: "Ensalada de quinoa, aguacate y aceite de oliva virgen extra (~500 kcal)." },
    ],
  },
];

// Restaurantes investigados vía búsqueda web (fuentes: Celicidad, Celiaquita, FACE y
// asociaciones territoriales, Glutiful, FindMeGlutenFree, TheFork, Restaurant Guru,
// webs oficiales). Notas de Google Maps tal y como se encontraron en el momento de la
// investigación: pueden cambiar con el tiempo. "aprox: true" marca notas tomadas de un
// agregador (no un pantallazo directo de Google Maps) o con cifras que variaban algo
// entre fuentes — trátalas con un margen de ±0.1-0.2.
const restaurantesPorCiudad = {
  madrid: {
    label: "Madrid",
    restaurantes: [
      { nombre: "Ardemos Burger", nota: 4.8, resenas: 7200, zona: "Chamberí", desc: "Hamburguesería 100% sin gluten, sin riesgo de contaminación cruzada." },
      { nombre: "Pizza Natura", nota: 4.8, resenas: 2340, zona: "Centro", desc: "Pizzería 100% sin gluten con masa de mijo y quinoa." },
      { nombre: "El Japo Carranza", nota: 4.7, resenas: 2784, zona: "Chamberí / Trafalgar", desc: "Restaurante japonés con cocina íntegramente sin gluten." },
      { nombre: "Okashi Sanda", nota: 4.7, resenas: null, zona: "Malasaña / Universidad", desc: "Primer japonés sin gluten de Madrid, certificado FACE." },
      { nombre: "Bastardi Ristorante", nota: 4.7, resenas: 30, zona: "Malasaña", desc: "Italiano 100% sin gluten, avalado por asociación de celíacos.", aprox: true },
      { nombre: "Solo de Croquetas", nota: 4.4, resenas: 3600, zona: "Centro / Salamanca", desc: "Especialista en croquetas 100% sin gluten y sin lactosa." },
      { nombre: "As de Bastos", nota: 4.3, resenas: null, zona: "Bellas Vistas / Tetuán", desc: "Menú mediterráneo 100% sin gluten." },
      { nombre: "LaLina Bravas y Tapas", nota: 4.3, resenas: 3645, zona: "La Latina", desc: "Bar de tapas y bravas prácticamente 100% sin gluten." },
      { nombre: "Llagar La Llobera", nota: 4.2, resenas: null, zona: "Chamberí", desc: "Asturiano 100% apto celíacos: fabada, cachopo, croquetas." },
    ],
  },
  barcelona: {
    label: "Barcelona",
    restaurantes: [
      { nombre: "Aruku Sushi Gluten Free", nota: 4.7, resenas: 1185, zona: "Eixample", desc: "Japonés 100% sin gluten (sushi, gyozas), cerveza sin gluten de barril." },
      { nombre: "Copasetic", nota: 4.6, resenas: 1300, zona: "Eixample", desc: "Café-restaurante con amplia carta sin gluten (crepes, hamburguesas, brunch)." },
      { nombre: "ApriBocca", nota: 4.5, resenas: null, zona: "Poblenou", desc: "Italiano avalado por ACELCAT, pasta fresca y pizza sin gluten.", aprox: true },
      { nombre: "Jansana", nota: 4.5, resenas: 3800, zona: "Eixample", desc: "Pastelería-café 100% sin gluten: panes, pizzas, bollería y tartas.", aprox: true },
      { nombre: "En Ville", nota: 4.5, resenas: 3500, zona: "Raval", desc: "Carta 100% sin gluten certificada por ACELCAT, cocina catalana/mediterránea.", aprox: true },
      { nombre: "Messié Pizza Gluten Free", nota: 4.5, resenas: 3060, zona: "Gràcia", desc: "Pizzería italiana 100% sin gluten, sin riesgo de contaminación cruzada.", aprox: true },
      { nombre: "Out of China", nota: 4.4, resenas: null, zona: "Eixample", desc: "Chino avalado por ACELCAT, +90% de la carta sin gluten.", aprox: true },
      { nombre: "L'Arrosseria Xàtiva", nota: 4.4, resenas: null, zona: "Sant Antoni", desc: "Especialistas en paella/arroces, variedades sin gluten certificadas ACELCAT.", aprox: true },
      { nombre: "Senza Glutine by Grosso Napoletano", nota: 4.2, resenas: null, zona: "Eixample", desc: "Pizzería napolitana 100% sin gluten (masa de arroz, maíz y trigo sarraceno)." },
    ],
  },
  valencia: {
    label: "Valencia",
    restaurantes: [
      { nombre: "Carlotes Café", nota: 4.9, resenas: 87, zona: "Ensanche / Extramurs", desc: "Cafetería 100% sin gluten certificada segura, personal formado en celiaquía." },
      { nombre: "Malkebien", nota: 4.7, resenas: 1446, zona: "Zona universitaria", desc: "Socio colaborador ACECOVA, pan y cerveza sin gluten." },
      { nombre: "Disidente", nota: 4.7, resenas: 431, zona: "Ensanche", desc: "Vegetariano con opciones sin gluten y gestión cuidadosa de alergias." },
      { nombre: "Civera Marisquería", nota: 4.6, resenas: 2000, zona: "Sant Francesc / centro", desc: "Marisquería histórica (desde los 60) incluida en el listado seguro de ACECOVA." },
      { nombre: "El Miracle", nota: 4.5, resenas: 2600, zona: "Pla del Remei / Gran Vía", desc: "Primer restaurante 100% sin gluten certificado por ACECOVA en la Comunidad Valenciana." },
      { nombre: "La Pappardella", nota: 4.5, resenas: 2200, zona: "La Seu", desc: "Italiana con carta asesorada por la asociación de celíacos." },
      { nombre: "Kuzina", nota: 4.5, resenas: 2000, zona: "Ciutat Vella, cerca de Ruzafa", desc: "Griega con amplia oferta sin gluten señalizada." },
      { nombre: "Casa Carmela", nota: 4.4, resenas: 8900, zona: "Malvarrosa", desc: "Icónica arrocería centenaria con acuerdo ACECOVA, pan sin gluten." },
      { nombre: "Al Pomodoro", nota: 4.4, resenas: 1300, zona: "La Xerea / Ciutat Vella", desc: "Pizzería italiana artesanal con opciones sin gluten, listada por Celicidad." },
      { nombre: "Mey Chen", nota: 4.3, resenas: 2700, zona: "Benimaclet", desc: "China avalada por ACECOVA, comanda diferenciada por plato." },
      { nombre: "LaLoLa Restaurante", nota: 4.3, resenas: 3150, zona: "La Seu, junto a la Catedral", desc: "Toda la carta de arroces y tapas es sin gluten (salvo el pan).", aprox: true },
      { nombre: "Mállalo X", nota: 4.1, resenas: 275, zona: "Mercado Central / Velluters", desc: "Acreditado por ACECOVA como local seguro." },
    ],
  },
  sevilla: {
    label: "Sevilla",
    restaurantes: [
      { nombre: "Restaurante Marroquí La Alcoba", nota: 4.8, resenas: 876, zona: "Santa Clara", desc: "Cocina marroquí con pastela y platos sin gluten, personal atento a intolerancias." },
      { nombre: "Barra Baja", nota: 4.7, resenas: 600, zona: "Casco Antiguo", desc: "Cocina de mercado andaluza de autor, miembro de la Red Sevilla Sin Gluten.", aprox: true },
      { nombre: "Acento - Social Eatery", nota: 4.7, resenas: 800, zona: "El Arenal / Casco Antiguo", desc: "Mediterráneo-internacional con atención específica a comensales celíacos." },
      { nombre: "Petit Comité", nota: 4.5, resenas: 2465, zona: "Casco Antiguo", desc: "Tapas de calidad, miembro de la Red Sevilla Sin Gluten-ASPROCESE." },
      { nombre: "Al Solito Posto", nota: 4.4, resenas: 4500, zona: "Alameda de Hércules", desc: "Italiano histórico homologado por la Asociación de Celíacos de Sevilla." },
      { nombre: "Señora Pan", nota: 4.4, resenas: null, zona: "Casco Antiguo", desc: "Restaurante 100% sin gluten, fusión español-venezolana." },
      { nombre: "Orfeo", nota: 4.2, resenas: 811, zona: "Casco Antiguo", desc: "Café-bar tranquilo, miembro de la Red Sevilla Sin Gluten-ASPROCESE." },
      { nombre: "Estragón", nota: 4.1, resenas: null, zona: "El Porvenir", desc: "Carta 100% sin gluten sin riesgo de contaminación cruzada, tapas y raciones." },
      { nombre: "Habanita", nota: 4.1, resenas: null, zona: "Casco Antiguo, junto a Plaza Alfalfa", desc: "Vegetariano/cubano con opciones sin gluten, más de 20 años de trayectoria." },
    ],
  },
  bilbao: {
    label: "Bilbao",
    restaurantes: [
      { nombre: "Casa Leotta – Pozas", nota: 4.7, resenas: null, zona: "Pozas / Abando", desc: "Pinsas y pasta 100% sin gluten, asesorados por EZE (Celíacos de Euskadi)." },
      { nombre: "Casa Leotta – Ajuriaguerra", nota: 4.6, resenas: 2192, zona: "Ajuriaguerra / Abando", desc: "Pinsas y pasta sin gluten dedicadas, avalado por EZE." },
      { nombre: "Kalí Órexi by Labocatorio", nota: 4.6, resenas: 1500, zona: "Abando (Fernández del Campo)", desc: "Gastrobar griego-mediterráneo con platos marcados sin gluten en carta." },
      { nombre: "Arraiz Asador", nota: 4.5, resenas: 1450, zona: "Arraiz (cerca de Artxanda)", desc: "Asador con certificación oficial FACE desde 2016.", aprox: true },
      { nombre: "Ahoan", nota: 4.2, resenas: null, zona: "Plaza Nueva / Casco Viejo", desc: "Bar de pintxos con cocina separada, dueños celíacos." },
      { nombre: "El Informal", nota: 4.2, resenas: 606, zona: "Indautxu / Ensanche", desc: "Mediterráneo-vasco con menú adaptado sin gluten y opciones vegetarianas." },
      { nombre: "Mandoya", nota: 4.1, resenas: null, zona: "Casco Viejo", desc: "Usa harina de garbanzo desde los años 90, amplio conocimiento de la celiaquía.", aprox: true },
      { nombre: "La Lonja de Olabeaga", nota: 4.0, resenas: null, zona: "Olabeaga", desc: "Cocina tradicional vasca a la brasa avalada por FACE desde 2024." },
      { nombre: "Larruzz", nota: 4.0, resenas: null, zona: "Uribitarte (junto al Guggenheim)", desc: "Certificado por EZE, protocolos anti-contaminación cruzada, arroces." },
    ],
  },
  malaga: {
    label: "Málaga",
    restaurantes: [
      { nombre: "Sushi Flower", nota: 4.8, resenas: 605, zona: "Perchel / Teatinos", desc: "Carta 98% sin gluten, extremo cuidado con la contaminación cruzada.", aprox: true },
      { nombre: "Reviv Café", nota: 4.8, resenas: 429, zona: "Centro Histórico", desc: "Cafetería 100% sin gluten y vegana, certificada por la Red Málaga Sin Gluten." },
      { nombre: "La Plancha Taberna", nota: 4.7, resenas: 140, zona: "El Perchel", desc: "Carta 100% sin gluten, certificada por la red Málaga Sin Gluten.", aprox: true },
      { nombre: "Mesón Mariano", nota: 4.7, resenas: 3000, zona: "Centro", desc: "Taberna tradicional desde 1988 que señala el gluten en cada plato." },
      { nombre: "Bibra Real Food Teatinos", nota: 4.6, resenas: 1098, zona: "Teatinos-Universidad", desc: "Red Málaga Sin Gluten, poke bowls y ensaladas sin contaminación cruzada." },
      { nombre: "El Taller de Larios 10", nota: 4.6, resenas: null, zona: "Centro (Calle Larios)", desc: "Restaurante en azotea con categoría sin gluten reconocida en TheFork." },
      { nombre: "Osteria Angelino dal 1899", nota: 4.6, resenas: 3659, zona: "Centro", desc: "Italiano con pasta sin gluten y alérgenos claramente marcados en carta." },
      { nombre: "Maldonado 21", nota: 4.5, resenas: 830, zona: "Ciudad Jardín", desc: "Especialista en fritura sin gluten con utensilios y platos separados." },
      { nombre: "El Tapeo de Cervantes", nota: 4.3, resenas: null, zona: "Centro", desc: "Bar de tapas de autor que marca el gluten en el menú." },
      { nombre: "Los Mellizos Soho", nota: 4.1, resenas: 2790, zona: "Soho", desc: "100% sin gluten certificado ACEMA, especializado en pescaíto frito y marisco.", aprox: true },
    ],
  },
  zaragoza: {
    label: "Zaragoza",
    restaurantes: [
      { nombre: "Labamba", nota: 4.8, resenas: 647, zona: "Casco Antiguo / Centro", desc: "Menú degustación de 6 pasos 100% sin gluten, cambia cada temporada." },
      { nombre: "Urbanita Gastrobar", nota: 4.8, resenas: null, zona: "Centro", desc: "Gastrobar 100% sin gluten con certificación oficial." },
      { nombre: "Restaurante Isla Sicilia (Con y Sin Gluten)", nota: 4.7, resenas: 1182, zona: "Casco Antiguo (Pl. del Pilar)", desc: "Italiano con dos cocinas separadas para evitar contaminación cruzada." },
      { nombre: "La Jaula de Grillos", nota: 4.6, resenas: null, zona: "Casco Antiguo", desc: "Primer establecimiento 100% sin gluten de Aragón (2016)." },
      { nombre: "Restaurante Baobab", nota: 4.6, resenas: 4079, zona: "Romareda", desc: "Vegetariano histórico (desde 2005) afiliado a la asociación de celíacos." },
      { nombre: "Mononoke Board Game Café", nota: 4.5, resenas: null, zona: "Centro / Delicias", desc: "Cafetería-ludoteca con carta de pizzas y cervezas artesanales sin gluten." },
      { nombre: "El Disfrutón", nota: 4.5, resenas: 690, zona: "Casco Histórico", desc: "Miembro de la Asociación Celíaca Aragonesa (ACA), carta mediterránea adaptada." },
      { nombre: "El Truco", nota: 4.4, resenas: 2000, zona: "El Tubo / Casco Antiguo", desc: "Bar de tapas 100% sin gluten, premiado varios años por sus croquetas." },
      { nombre: "Costa 8 Gastrobar", nota: 4.3, resenas: null, zona: "Centro", desc: "Certificado por la Asociación Celíaca de Aragón (ACA)." },
      { nombre: "La Antilla", nota: 4.3, resenas: 475, zona: "Varios locales", desc: "Pan sin gluten, muy recomendada avisando con antelación." },
      { nombre: "BuleBar Zentro", nota: 4.1, resenas: 1664, zona: "Centro", desc: "Arrocería/paellas con especialidades sin gluten bajo petición." },
    ],
  },
  alicante: {
    label: "Alicante",
    restaurantes: [
      { nombre: "Distópico", nota: 4.9, resenas: 380, zona: "Centro", desc: "Cocina mediterránea de fusión; sus croquetas llevan el sello de garantía ACECOVA." },
      { nombre: "Punto de Uva", nota: 4.8, resenas: null, zona: "Centro", desc: "Vinoteca/tapas de autor 100% sin gluten avalada por ACECOVA." },
      { nombre: "Kazoku Sushi Restaurant", nota: 4.7, resenas: 250, zona: "Cabo de las Huertas", desc: "Japonés con carta específica sin gluten y control de contaminación cruzada." },
      { nombre: "Vértice Cervecería Bulevar", nota: 4.6, resenas: 100, zona: "Bulevar / Ciudad de Asís", desc: "Más del 80% de la carta apta para celíacos." },
      { nombre: "La Taverna dell'Artista", nota: 4.5, resenas: 1700, zona: "Centro (Pl. San Cristóbal)", desc: "Pizzería italiana 100% sin gluten certificada por ACECOVA.", aprox: true },
      { nombre: "Rice&Bones", nota: 4.5, resenas: 100, zona: "Centro", desc: "Único arrocero de Alicante certificado 100% sin gluten por ACECOVA." },
      { nombre: "La Taverna del Racó del Pla", nota: 4.5, resenas: 650, zona: "Centro (C. San Mateo)", desc: "Taberna urbana de arroces y tapas; pan sin gluten y protocolos de seguridad." },
      { nombre: "Apache Burger Grill", nota: 4.4, resenas: 800, zona: "Playa de San Juan", desc: "Hamburguesería premiada, freidora y panes sin gluten separados.", aprox: true },
      { nombre: "Oz Gastroclub", nota: 4.4, resenas: 540, zona: "Playa de San Juan", desc: "Carta prácticamente 100% sin gluten certificada por ACECOVA." },
      { nombre: "Askuabarra Alicante", nota: 4.4, resenas: 200, zona: "Centro", desc: "Bar de pinchos/tapas con amplia oferta sin gluten." },
    ],
  },
  castellon: {
    label: "Castellón",
    restaurantes: [
      { nombre: "Can Celiac", nota: 4.8, resenas: 195, zona: "Centro", desc: "Panadería-café 100% sin gluten, elaboración diaria sin contaminación cruzada." },
      { nombre: "GoodFood Gastro Bar", nota: 4.8, resenas: 25, zona: "Centro", desc: "Gastrobar pequeño con toda la carta 100% sin gluten.", aprox: true },
      { nombre: "L'Etrusco", nota: 4.6, resenas: 1700, zona: "Centro", desc: "Italiano avalado por ACECOVA, elaboración y carta adaptadas.", aprox: true },
      { nombre: "Little Thai Castellón", nota: 4.6, resenas: null, zona: "Centro (Av. Rei En Jaume)", desc: "Cocina tailandesa con platos sin gluten marcados en carta." },
      { nombre: "Peltre Cuina Mexicana", nota: 4.6, resenas: 1060, zona: "Centro", desc: "Cocina mexicana muy bien valorada, con opciones sin gluten cuidadas." },
      { nombre: "Corpore Sano Duo", nota: 4.5, resenas: 183, zona: "Centro", desc: "Restaurante 100% sin gluten certificado por ACECOVA, cocina saludable." },
      { nombre: "Le Otto Sin Gluten", nota: 4.5, resenas: null, zona: "Centro", desc: "Pizzería 100% sin gluten, horno exclusivo sin riesgo de trazas." },
      { nombre: "El Colmado", nota: 4.4, resenas: 130, zona: "Junto al Mercado Central", desc: "Taberna con utensilios duplicados para evitar contaminación cruzada." },
      { nombre: "Lino Gastronomic", nota: 4.4, resenas: null, zona: "Casco histórico", desc: "Carta de arroces con opciones aptas para celíacos." },
    ],
  },
};

// Tiendas cuyo negocio principal es la venta de productos sin gluten (no
// supermercados generalistas). Investigadas vía búsqueda web en septiembre de
// 2026: nombres y ubicaciones verificados, pero las notas de Google y el nº de
// reseñas proceden en su mayoría de agregadores de búsqueda, no de una consulta
// directa a Google Maps — trátalas como orientativas ("aprox: true" cuando la
// fuente lo advierte explícitamente). "web: null" significa que no se encontró
// un sitio oficial propio confirmado con confianza razonable.
const tiendasEspecializadas = [
  {
    nombre: "Artediet",
    tipo: "Física",
    ciudad: "Madrid",
    desc: "Panadería y pastelería 100% sin gluten: pan, bollería, dulces y salados.",
    nota: 4.8,
    resenas: 185,
    web: "https://www.artediet.es/",
  },
  {
    nombre: "Gluten Tag",
    tipo: "Física",
    ciudad: "Barcelona (Gràcia)",
    desc: "Obrador sin gluten especializado en bollería, pan y dulces.",
    nota: 4.8,
    resenas: 159,
    web: "https://www.glutentag.cat",
  },
  {
    nombre: "Celiacs & Co",
    tipo: "Física",
    ciudad: "Barcelona (La Sagrera)",
    desc: "Supermercado especializado sin gluten (también sin lactosa y opciones veganas).",
    nota: 4.8,
    resenas: null,
    aprox: true,
    web: "https://celiacsandco.com/",
  },
  {
    nombre: "Glutery",
    tipo: "Física",
    ciudad: "Barcelona (Gràcia)",
    desc: "Café-obrador sin gluten certificado por Celíacs Catalunya, conocido por empanadas y focaccia.",
    nota: 4.7,
    resenas: null,
    aprox: true,
    web: null,
  },
  {
    nombre: "Maná Productos Sin Gluten",
    tipo: "Física y online",
    ciudad: "Madrid (Salamanca)",
    desc: "Supermercado especializado sin gluten con más de 600 referencias de varias marcas.",
    nota: 4.2,
    resenas: 121,
    web: "https://www.manaproductossingluten.com/",
  },
  {
    nombre: "Celicioso",
    tipo: "Física",
    ciudad: "Madrid (varios locales, también Marbella y Palma)",
    desc: "Pastelería-cafetería 100% sin gluten: bollería americana, dulce y salado.",
    nota: 3.9,
    resenas: null,
    aprox: true,
    web: null,
  },
  {
    nombre: "Sana Locura Gluten Free Bakery",
    tipo: "Física",
    ciudad: "Barcelona (Sant Gervasi)",
    desc: "Panadería y pastelería 100% sin gluten.",
    nota: 3.5,
    resenas: 84,
    web: "https://sanalocura.es/",
  },
  {
    nombre: "La Celiacoteca",
    tipo: "Física",
    ciudad: "Madrid / Alcalá de Henares",
    desc: "Obrador 100% sin gluten: panadería, bollería y masas saladas.",
    nota: null,
    resenas: null,
    web: "https://www.laceliacoteca.com/index.html",
  },
  {
    nombre: "Món Celíac",
    tipo: "Física y online",
    ciudad: "Barcelona",
    desc: "Obrador 100% sin gluten: pan, dulces y snacks, con envío a la península.",
    nota: null,
    resenas: null,
    web: "https://monceliac.com/",
  },
  {
    nombre: "Celikatessen",
    tipo: "Física",
    ciudad: "Madrid (Mercado de Pacífico)",
    desc: "Panadería y repostería ecológica sin gluten y sin lácteos.",
    nota: null,
    resenas: null,
    web: null,
  },
  {
    nombre: "Celicientos",
    tipo: "Física",
    ciudad: "Valencia",
    desc: "Panadería-cafetería 100% sin gluten, dulce y salado, con reparto a domicilio.",
    nota: null,
    resenas: null,
    web: "https://celicientos.com/",
  },
  {
    nombre: "El Obrador del Celíaco",
    tipo: "Física",
    ciudad: "Valencia",
    desc: "Panadería y pastelería sin gluten y sin lactosa: pan rústico, fartons, tartas.",
    nota: null,
    resenas: null,
    web: null,
  },
  {
    nombre: "Panceliac",
    tipo: "Online",
    ciudad: "Envío a toda España",
    desc: "Panadería, bollería y alimentación sin gluten con envío a domicilio.",
    nota: null,
    resenas: null,
    web: "https://panceliac.com/",
  },
  {
    nombre: "Glutenfreeshop.es",
    tipo: "Online",
    ciudad: "Envío a la península",
    desc: "Selección gourmet de alimentos ecológicos sin gluten, suplementos y libros.",
    nota: null,
    resenas: null,
    web: "https://glutenfreeshop.es/",
  },
];
