const supermercadoCategories = [
  {
    icon: "🍞",
    iconClass: "icon-1",
    title: "Panadería y bollería",
    text: 'Pan de molde sin gluten, baguettes certificadas y bollería (Schär, Proceli, líneas "Sin Gluten" de supermercado).',
    productos: [
      "Hacendado (Mercadona) — Pan de molde blanco sin gluten",
      "Hacendado (Mercadona) — Baguette sin gluten",
      "Hacendado (Mercadona) — Pan de hamburguesa sin gluten",
      "Schär — Pan de molde (Pan Carré)",
      "Proceli — Pan tradicional sin gluten",
      "Beiker — Pan de molde sin gluten",
      "Adpan — Chapata sin gluten",
      "Carrefour Sin Gluten — Magdalenas y bollería sin gluten",
      "Gerblé — Pan payés con semillas sin gluten",
      "Gerblé — Pan burger (hamburguesa) sin gluten, a la harina de soja",
      "Schär — Pan de molde con cereales",
      "Schär — Panecillos (Bridge Rolls) sin gluten",
      "Proceli — Pan de molde Complet",
      "Hacendado (Mercadona) — Magdalena de coco sin gluten",
    ],
  },
  {
    icon: "🍝",
    iconClass: "icon-2",
    title: "Pasta y arroz",
    text: "Pasta de maíz y arroz, fideos sin gluten y arroces certificados para todo tipo de recetas.",
    productos: [
      "Hacendado (Mercadona) — Pasta sin gluten: fusilli, espagueti, estrellas (maíz y arroz)",
      "Gallo — Pasta sin gluten (spaghetti, macarrones, tiburones)",
      "Barilla — Pasta senza glutine",
      "Schär — Pasta Anellini",
      "Carrefour Sin Gluten — Macarrones y espirales",
      "El Granero Integral — Pasta de trigo sarraceno sin gluten",
      "Hacendado (Mercadona) — Pasta rellena sin gluten (harina de arroz y maíz)",
      "Barilla — Penne Rigate sin gluten",
      "Gallo — Pasta de lentejas rojas sin gluten",
      "Schär — Pasta Fusilli sin gluten",
      "El Granero Integral — Arroz integral Bio",
    ],
  },
  {
    icon: "🍿",
    iconClass: "icon-3",
    title: "Snacks y aperitivos",
    text: "Patatas fritas certificadas, palomitas naturales y frutos secos sin trazas de gluten.",
    productos: [
      "Hacendado (Mercadona) — Patatas fritas sin gluten",
      'Carrefour — Snacks "mios!" sin gluten',
      "Lay's — Patatas fritas sin gluten",
      "Ruffles — Patatas fritas sin gluten",
      "Grefusa — Snacks sin gluten",
      "Risi — Snacks de arroz sin gluten",
      "Proceli — Picos/colines sin gluten (aceite de oliva virgen extra)",
      "Risi — Risketos, snack de maíz horneado sin gluten",
      "Risi — Palomitas de maíz sin gluten",
      "Risi — Palomitas recubiertas de chocolate sin gluten",
      "Carrefour Sin Gluten — Tortitas de maíz/arroz",
      "Carrefour Sin Gluten — Palomitas",
    ],
  },
  {
    icon: "🥣",
    iconClass: "icon-4",
    title: "Desayuno y cereales",
    text: "Avena certificada sin gluten, cereales de maíz o arroz y galletas de líneas sin gluten.",
    productos: [
      "Hacendado (Mercadona) — Corn Flakes sin gluten (Harvest Home)",
      "Hacendado (Mercadona) — Muesli crunchy chocolate sin gluten",
      "Santiveri (Noglut) — Cereales cacao y miel sin gluten",
      "Santiveri (Noglut) — Corn Flakes sin gluten",
      "Santiveri (Noglut) — Muesli frutas y frutos secos sin gluten",
      "Schär — Cereales de desayuno sin gluten",
      "Nestlé — Corn Flakes sin gluten",
      "Kellogg's — Cereales sin gluten (Dia)",
      "Go Free — Copos de maíz tostados sin gluten",
      "Gerblé — Tostadas de maíz y arroz sin gluten",
      "Gerblé — Galletas de desayuno a la harina de arroz sin gluten",
    ],
  },
  {
    icon: "🧂",
    iconClass: "icon-5",
    title: "Salsas y condimentos",
    text: "Salsa de soja sin gluten (tamari), caldos certificados y especias puras sin aditivos.",
    productos: [
      "Hacendado (Mercadona) — Salsa de soja sin gluten",
      "Hacendado (Mercadona) — Mayonesa ligera sin gluten",
      "Hacendado (Mercadona) — Kétchup sin gluten",
      "Carrefour Sin Gluten — Salsa barbacoa y salsa de soja",
      "Ybarra — Mayonesa y kétchup sin gluten",
      "Schär — Salsa boloñesa y pesto sin gluten",
      "Hellmann's — Mostaza sin gluten",
      "Hellmann's — Salsa mostaza y miel sin gluten",
      "Hellmann's — Salsa barbacoa dulce sin gluten",
      "Ybarra — Salsa miel y mostaza sin gluten",
      "Ybarra — Salsa Alioli/Gaucha sin gluten",
      "Orlando — Tomate frito sin gluten",
    ],
  },
  {
    icon: "🧊",
    iconClass: "icon-6",
    title: "Congelados",
    text: "Pizzas sin gluten, empanados de maíz y rebozados certificados listos para hornear.",
    productos: [
      "Hacendado (Mercadona) — Pizza 4 quesos sin gluten y sin lactosa",
      "Hacendado (Mercadona) — Bases de pizza sin gluten y sin lactosa",
      "Hacendado (Mercadona) — Pan rallado sin gluten",
      "Hacendado (Mercadona) — Placas de canelones/lasaña precocidas sin gluten (maíz y arroz)",
      "Frisa — Croquetas \"Caprichos de Jamón\" sin gluten (Mercadona)",
      "Carrefour Sin Gluten — Pizza congelada",
      "La Cocinera — Nuggets de pollo sin gluten (rebozados con harina de arroz y garbanzo)",
      "Hacendado (Mercadona) — San Jacobos de cerdo sin gluten",
      "Schär — Pizza congelada 4 quesos sin gluten (Alcampo)",
      "Schär — Base de pizza congelada sin gluten",
    ],
  },
  {
    icon: "🥤",
    iconClass: "icon-7",
    title: "Bebidas",
    text: "Cerveza sin gluten, horchata y batidos certificados aptos para celíacos.",
    productos: [
      "Damm — Cerveza Daura sin gluten",
      "Damm — Daura Märzen sin gluten",
      "Chufi — Horchata de chufa (naturalmente sin gluten)",
      "Hacendado (Mercadona) — Horchata de chufa sin gluten",
      "ColaCao — Cacao soluble sin gluten",
      "Puleva — Batido sin gluten",
      "Estrella Galicia — Cerveza Sin Gluten",
      "Mahou — Cerveza Sin Gluten",
      "Ambar — Especial Sin Gluten",
      "Ambar — 0,0 Sin Gluten (sin alcohol)",
      "Free Damm — Cerveza 0,0 sin gluten",
    ],
  },
  {
    icon: "🍫",
    iconClass: "icon-8",
    title: "Dulces y postres",
    text: "Chocolate sin gluten, bizcochos y turrones certificados en temporada.",
    productos: [
      "Hacendado (Mercadona) — Galletas María sin gluten y sin lactosa",
      "Hacendado (Mercadona) — Cookies con chispas de chocolate sin gluten",
      "Hacendado (Mercadona) — Bizcocho de chocolate sin gluten y sin lactosa",
      "Gullón — Galletas María sin gluten",
      "Gullón — Sharkies sin gluten (infantil)",
      "Gullón — Digestive sin gluten",
      "Proceli — Bizcochitos rellenos (Petite Fraise / Petite Délice)",
      "Gullón Diet Nature — Digestive sin azúcar, sin gluten",
      "Gerblé — Galletas con chispas de chocolate sin gluten",
      "Delaviuda — Turrón duro sin gluten",
      "Hacendado (Mercadona) — Bizcocho de limón sin gluten",
      "Valor — Chocolate negro 85% sin azúcares añadidos, sin gluten",
      "Valor — Postres de chocolate negro 70% sin gluten",
    ],
  },
  {
    icon: "🧀",
    iconClass: "icon-9",
    title: "Lácteos y alternativas",
    text: "Quesos naturales, yogures sin aditivos y bebidas vegetales (avena, soja, almendra) certificadas sin gluten.",
    productos: [
      "Hacendado (Mercadona) — Yogur natural sin gluten",
      "Hacendado (Mercadona) — Postre lácteo cremoso sin lactosa y sin gluten",
      "Hacendado (Mercadona) — Bebida de avena sin gluten",
      "Alpro — Bebida de avena sin gluten certificada",
      "Central Lechera Asturiana — Bebida de avena sin gluten",
      "Hacendado (Mercadona) — Skyr sin gluten",
      "Vivesoy — Bebida de avena sin azúcar",
      "Vivesoy — Bebida de frutos secos sin azúcar",
      "Kaiku Begetal — Bebida vegetal de avena/almendra",
      "Alpro (Danone) — Postre vegetal de coco natural",
      "Alpro (Danone) — Frutos rojos y dátiles sin azúcares añadidos",
    ],
  },
  {
    icon: "🥫",
    iconClass: "icon-10",
    title: "Legumbres y conservas",
    text: "Legumbres cocidas al natural y conservas de pescado en aceite de oliva o al natural, sin aditivos con gluten.",
    productos: [
      "Hacendado (Mercadona) — Garbanzos cocidos sin gluten",
      "Hacendado (Mercadona) — Lenteja pardina cocida sin gluten",
      "Hacendado (Mercadona) — Alubias blancas cocidas sin gluten",
      "Hacendado (Mercadona) — Atún en aceite de oliva sin gluten",
      "Litoral — Legumbres cocidas sin gluten",
      "El Granero Integral — Legumbres ecológicas sin gluten",
      "Carrefour Sin Gluten — Legumbres cocidas",
      "Luengo — Legumbres cocidas sin gluten",
      "Cidacos — Legumbres en conserva",
      "Carretilla — Fabada asturiana sin gluten",
      "Calvo — Atún claro en aceite de oliva sin gluten",
      "Isabel — Atún claro en aceite de girasol alto oleico, sin gluten y sin lactosa",
    ],
  },
  {
    icon: "🌾",
    iconClass: "icon-11",
    title: "Harinas y repostería",
    text: "Harina de arroz, maíz y almendra, y mezclas panificables certificadas para hornear en casa.",
    productos: [
      "Hacendado (Mercadona) — Preparado para panificación y repostería sin gluten",
      "Hacendado (Mercadona) — Preparado para bizcocho sin gluten",
      "Schär — Mix B Pan (harina panificable sin gluten)",
      "El Granero Integral — Harina de arroz sin gluten",
      "El Granero Integral — Harina de trigo sarraceno sin gluten",
      "Beiker — Preparado panificable sin gluten",
      "Adpan — Mix panadera sin gluten",
      "NaturGreen — Harina de trigo sarraceno Bio sin gluten",
      "NaturGreen — Harina de arroz integral Bio sin gluten",
      "NaturGreen — Harina de garbanzo Bio sin gluten",
      "NaturGreen — Harina de avena integral Bio sin gluten",
      "NaturGreen — Mezcla de harina para pan Bio sin gluten",
      "Ceresin — Preparado panificable y de repostería sin gluten",
    ],
  },
  {
    icon: "👶",
    iconClass: "icon-12",
    title: "Alimentación infantil",
    text: "Potitos, papillas y galletas de iniciación certificados sin gluten para bebés y niños.",
    productos: [
      "Nestlé — Papilla de cereales sin gluten (crema de arroz)",
      "Nestlé — Papilla maíz y arroz sin gluten",
      "Blevit (Ordesa) — Blevit Plus Bibe sin gluten (arroz y maíz)",
      "Nutribén — Papilla de cereales sin gluten",
      "Hero Baby — Papilla de cereales sin gluten",
      "Smileat — Potitos y papillas ecológicas sin gluten",
      "Hacendado (Mercadona) — Potitos de fruta (naturalmente sin gluten)",
      "Nutribén — Harina Vegetal Primera Papilla sin gluten y sin lactosa",
      "Hero Solo — Papilla de cereales sin gluten",
      "Hero Baby Pedialac — Papilla de cereales sin gluten",
      "Holle — Papilla de 3 cereales sin gluten Bio",
      "Gerber (Nestlé) — Papilla de arroz sin gluten",
    ],
  },
];

// Catálogo sin gluten por supermercado. Cada clave de "categorias" debe
// coincidir con un "title" de supermercadoCategories (se reutiliza su
// icono). Solo se listan categorías con productos verificados vía
// búsqueda web para esa cadena concreta — si una cadena no tiene una
// categoría, es porque no se encontraron datos fiables, no porque no
// venda nada sin gluten ahí.
const supermercadosCatalogo = {
  mercadona: {
    label: "Mercadona",
    categorias: {
      "Panadería y bollería": [
        "Hacendado — Pan de molde sin gluten blanco",
        "Hacendado — Pan de molde multicereales sin gluten",
        "Hacendado — Pan de molde cereales sin gluten",
        "Hacendado — Magdalenas sin gluten",
        "Hacendado — Picos sin gluten",
        "Hacendado — Tostadas sin gluten",
        "Hacendado — Polvorones sin gluten (navideño, producto estacional)",
      ],
      "Pasta y arroz": [
        "Hacendado — Fusilli sin gluten (harina de maíz y arroz)",
        "Hacendado — Espaguetis sin gluten",
        "Hacendado — Macarrones/Coditos sin gluten",
        "Hacendado — Penne/macarrones de harina de avena y maíz sin gluten",
        "Felicia (en Mercadona) — Spaghetti sin gluten",
      ],
      "Snacks y aperitivos": [
        "Hacendado — Patatas fritas 0% sal añadida sin gluten",
        "Hacendado — Patatas fritas extra crujientes",
        "Hacendado — Maíz palomitas natural para microondas",
        "Hacendado — Palomitas de maíz dulces para microondas",
        "Hacendado — Crackers sin gluten con romero",
        "Hacendado — Triángulos de maíz sin gluten",
        "Hacendado — Nachos sin gluten",
        "Hacendado — Tortitas de maíz sin gluten",
      ],
      "Desayuno y cereales": [
        "Hacendado — Cereales rellenos de crema de cacao y avellana sin gluten",
        "Hacendado — Copos de avena sin gluten",
        "Hacendado — Copos de maíz (Corn Flakes) 0% azúcares añadidos sin gluten",
      ],
      "Salsas y condimentos": ["Hacendado — Salsa de soja sin gluten"],
      Congelados: [
        "Hacendado — Pizza 4 quesos sin gluten y sin lactosa (ultracongelada)",
        "Hacendado — Bases de pizza sin gluten y sin lactosa (ultracongeladas)",
        "Hacendado — Arroz tres delicias ultracongelado sin gluten",
        "Hacendado — Croquetas de jamón sin gluten (línea Caprichos)",
        "Hacendado — Nuggets de pollo sin gluten",
      ],
      Bebidas: [
        "Mahou — Cerveza sin gluten 0,0% sin alcohol tostada",
        "Free Damm — Cerveza sin gluten 0,0% sin alcohol",
        "Hacendado — Bebida de avena 0% azúcar sin gluten",
        "Mercadona — Cerveza Steinburg 0,0 sin gluten",
      ],
      "Dulces y postres": [
        "Hacendado — Bizcocho de chocolate sin gluten",
        "Hacendado — Bizcocho de chocolate sin gluten y sin lactosa",
        "Hacendado — Turrón crema de almendras 0% azúcares añadidos sin gluten",
        "Hacendado — Cookies sin gluten y sin lactosa con pepitas de chocolate",
        "Hacendado — Flan de queso sin gluten",
        "Hacendado — Flan de huevo alto en proteínas sin gluten",
      ],
      "Lácteos y alternativas": [
        "Hacendado — Queso fresco batido 0% sin gluten",
        "Hacendado — Bebida de avena sin gluten",
        "Alpro — Bebida de avena/soja sin gluten",
        "Hacendado — Bebida de almendras con calcio sin gluten",
        "Hacendado — Bebida de almendras Zero sin gluten",
      ],
      "Legumbres y conservas": [
        "Hacendado — Garbanzos cocidos a la jardinera sin gluten",
        "Hacendado — Fusilli de lentejas rojas (100% harina de lentejas, sin gluten)",
        "Hacendado — Garbanzo cocido en tarro sin gluten",
      ],
      "Harinas y repostería": [
        "Hacendado — Harina de maíz fina precocinada sin gluten",
        "Hacendado — Harina de garbanzo sin gluten",
        "Hacendado — Preparado para bizcocho sin gluten",
        "Hacendado — Preparado para panificación y repostería sin gluten",
        "Hacendado — Pan rallado sin gluten",
      ],
      "Alimentación infantil": [
        "Hero Baby — Papilla sin gluten crema de arroz +4 meses",
        "Nestlé — Papilla maíz y arroz sin gluten +4 meses",
        "Hacendado — Potitos de fruta sin azúcares añadidos, sin gluten",
        "Hacendado — Galleta para bebé sin gluten y sin lactosa",
      ],
    },
  },
  carrefour: {
    label: "Carrefour",
    categorias: {
      "Panadería y bollería": [
        "Carrefour No Gluten — Pan de molde Classic sin gluten",
        "Carrefour No Gluten — Pan de molde con semillas sin gluten",
        "Carrefour No Gluten — Magdalenas redondas sin gluten y sin lactosa",
        "Carrefour No Gluten — Magdalenas valencianas sin gluten y sin lactosa",
        "Carrefour No Gluten — Croissant Classic sin gluten",
        "Carrefour No Gluten — Baguette sin gluten",
        "Carrefour No Gluten — Pan hamburguesa sin gluten y sin lactosa",
        "Carrefour Classic — Pan para bocadillo sin gluten y sin lactosa",
        "Carrefour Classic — Picos de pan con aceite de oliva sin gluten y sin lactosa",
        "Proceli (en Carrefour) — Pan chapata rústico sin gluten y sin lactosa",
      ],
      "Pasta y arroz": [
        "Carrefour Classic No Gluten — Espaguetis de maíz y arroz",
        "Carrefour Classic No Gluten — Macarrones de maíz y arroz",
        "Carrefour Classic No Gluten — Espirales de maíz y arroz",
        "Carrefour Classic — Arroz blanco cocido sin gluten",
        "Gallo — Placas para lasaña y canelones sin gluten",
        "Carrefour Classic No Gluten — Fideos de maíz",
      ],
      "Snacks y aperitivos": [
        "Risi — Risketos sin gluten",
        "Risi — Triskys sin gluten",
        'Risi Mios! — Aperitivo de maíz sabor tomillo y limón sin gluten',
        "Risi Mios! — Aperitivo de maíz y chía con sal marina sin gluten",
        "Mission — Tortillas de maíz y arroz sin gluten",
        "Risi — Risketos Ligeros sin gluten",
        "Risi Mios! — Aperitivo de maíz y boletus sabor cebolla caramelizada sin gluten",
        "Snatt's (Grefusa, en Carrefour) — Natuchips tomate, queso y orégano sin gluten",
      ],
      "Desayuno y cereales": [
        "Carrefour Classic — Corn flakes sin gluten y sin azúcar añadido",
        "Carrefour Sensation — Muesli crujiente sin gluten y sin azúcar añadido",
        "Nestlé — Cereales de maíz Corn Flakes sin gluten",
        "Gullón — Galletas María sin gluten y sin lactosa",
        "Gullón — Galletas Digestive sin gluten y sin lactosa",
      ],
      "Salsas y condimentos": [
        "Kikkoman — Salsa de soja sin gluten",
        "Kikkoman — Salsa de soja Tamari sin gluten",
        "Tiger Khan — Salsa de soja tradicional Gold sin gluten",
        "Carrefour Classic — Ketchup sin gluten y sin azúcar añadido",
        "Selection Carrefour & Lord Dani — Salsa Bull sin gluten",
      ],
      Congelados: [
        "Carrefour Classic — Base de pizza sin gluten",
        "Pescanova — Nuggets de merluza sin gluten",
        "Pescanova — Varitas popcorn de merluza sin gluten",
        "Gallo — Placas para lasaña y canelones sin gluten",
        "Schär (en Carrefour) — Pizza margarita sin gluten y sin lactosa",
        "Casa Tarradellas (en Carrefour) — Pizza de jamón y queso sin gluten y sin lactosa",
        "La Cocina de Senén (en Carrefour) — Croqueta de jamón y pan crujiente sin gluten",
        "La Cocina de Senén (en Carrefour) — Croquetas de pollo campero sin gluten",
        "Fridela (en Carrefour) — Croquetas de jamón sin gluten",
      ],
      Bebidas: [
        "Carrefour Sensation — Cerveza artesana Radler sin gluten",
        "Carrefour Sensation — Cerveza artesana sin gluten",
        "Damm — Cerveza Free Damm 0,0 sin alcohol y sin gluten",
        "Damm — Cerveza Daura sin gluten",
      ],
      "Dulces y postres": [
        "Carrefour Sensation — Turrón blando crujiente sin gluten",
        "Carrefour Sensation — Turrón crujiente de chocolate blanco con galleta negra sin gluten",
        "Carrefour Sensation — Turrón duro sin gluten",
        "Carrefour Sensation — Turrón blando sin gluten",
        "Carrefour Sensation — Turrón praliné de pistacho sin gluten",
        "Carrefour Sensation — Turrón de guirlache sin gluten",
        "Selection Carrefour & Lord Dani — Turrón de crema de almendra con venas de chocolate 70% y sal, sin gluten",
      ],
      "Lácteos y alternativas": [
        "Carrefour — Bebida de soja sin azúcar añadido sin gluten",
        "YoSoy — Bebida de avena sin gluten",
        "YoSoy — Bebida de avena ecológica sin gluten",
        "Carrefour Bio — Bebida de almendras sin azúcar añadido ecológica sin gluten",
      ],
      "Legumbres y conservas": [
        "Carrefour Simply — Garbanzos cocidos",
        "Carrefour Classic — Alubias con verduras sin gluten",
        "Litoral — Fabada Asturiana sin gluten",
        "Litoral (Hoy Legumbres) — Garbanzos con su sofrito sin gluten",
        "Litoral (Hoy Legumbres) — Lentejas de la abuela sin gluten",
        "Litoral — Lentejas a la riojana sin gluten",
        "Litoral — Callos a la madrileña sin gluten",
        "Litoral — Cocido madrileño sin gluten",
        "Litoral — Cocido madrileño -30% sal y grasas sin gluten",
        "Carrefour Classic — Cocido madrileño sin gluten",
      ],
      "Harinas y repostería": [
        "Carrefour No Gluten — Preparado panificable Extra sin gluten y sin lactosa",
        "Carrefour No Gluten — Harina para pan y pastelería sin gluten",
        "Carrefour Classic No Gluten — Preparado para bizcocho sin gluten",
        "Schär (en Carrefour) — Harina para repostería sin gluten",
        "Schär (en Carrefour) — Preparado para pan sin gluten y sin lactosa",
      ],
      "Alimentación infantil": [
        "Carrefour Baby Bio — Papilla infantil con cereales desde 4 meses, ecológica, sin gluten",
      ],
    },
  },
  lidl: {
    label: "Lidl",
    categorias: {
      "Panadería y bollería": [
        "La Cestera — Pan de molde sin gluten",
        "La Cestera — Magdalenas sin gluten",
        "La Cestera — Bizcocho de chocolate sin gluten",
        "La Cestera — Palitos sin gluten",
        "La Cestera — Panecillos de hamburguesa rústicos sin gluten",
        "La Cestera — Pan maxi burger sin gluten",
      ],
      "Pasta y arroz": [
        "Combino — Penne sin gluten (maíz y arroz)",
        "Vitasia — Fideos de arroz",
        "Vitasia — Noodles de konjac sin gluten",
        "Combino — Macarrones sin gluten",
        "Combino — Espaguetis sin gluten",
      ],
      "Snacks y aperitivos": [
        "Snack Day — Patatas fritas sin gluten con aceite de oliva",
        "Sondey — Tortitas de maíz sin gluten",
        "Alesto — Frutos secos naturales",
        "Snack Day — Nachos sin gluten",
      ],
      "Desayuno y cereales": [
        "Crownfield — Copos de maíz tostados sin gluten (Corn Flakes)",
        "Sondey Bio Organic — Tortita de arroz con coco y chocolate con leche sin gluten",
      ],
      Congelados: [
        "Lidl — Nuggets de pollo sin gluten y sin lactosa",
        "Dr. Oetker Ristorante — Pizza Prosciutto sin gluten y sin lactosa",
      ],
      Bebidas: ["Sanwald — Cerveza sin gluten (avalada por FACE)"],
      "Dulces y postres": [
        "Sondey — Cookies de chocolate sin gluten (veganas)",
        "Sondey — Galletas María sin gluten",
        "Gelatelli — Helados sin gluten",
        "Sondey — Choco chip cookies de cacao sin gluten",
        "Sondey — Galletas rellenas de chocolate sin gluten",
      ],
      "Lácteos y alternativas": [
        "Milbona — Yogures sin gluten (natural y sabores)",
        "Vemondo — Bebida vegetal de arroz y quinoa sin gluten",
      ],
      "Harinas y repostería": [
        "Belbake — Harina/preparado sin gluten para pan y pizza",
        "Belbake — Preparado panificable sin gluten (pan blanco)",
      ],
    },
  },
  dia: {
    label: "Dia",
    categorias: {
      "Panadería y bollería": [
        "El Molino de Dia — Magdalenas sin gluten (también sin lactosa)",
        "Panceliac (Dia) — Picos sin gluten",
        "Panceliac (Dia) — Pan rallado sin gluten",
        "Panceliac (Dia) — Pan de molde sin gluten",
        "Dia Sin Gluten — Pan de molde y panecillos de hamburguesa sin gluten",
        "El Molino de Dia — Bocadito marmolado sin gluten",
        "Proceli (en Dia) — Pan tradicional sin gluten",
        "Proceli (en Dia) — Biscotes sin gluten",
        "Esgir (en Dia) — Preparado para rebozar crujiente sin gluten",
      ],
      "Pasta y arroz": [
        "Gallo (Dia) — Espaguetis sin gluten",
        "Gallo (Dia) — Macarrones sin gluten",
        "Dia Sin Gluten — Pasta sin gluten (gama propia)",
        "Dia Al Diante — Espaguetis sin gluten",
        "Gallo (Dia) — Pasta hélices 100% lentejas rojas sin gluten",
        "Gallo (Dia) — Pasta hélices 100% garbanzo sin gluten",
      ],
      "Snacks y aperitivos": [
        "Snack Maniac (Dia) — Patatas fritas gourmet extra crujientes sin gluten",
        "Snack Maniac (Dia) — Patatas fritas campesinas sin gluten",
        "Snack Maniac (Dia) — Torzitos sabor queso sin gluten",
        "Snack Maniac (Dia) — Nachos sabor queso tex-mex sin gluten",
        "Tosfrit (Dia) — Aros de maíz frito sin gluten",
        "Snack Maniac (Dia) — Patatas fritas sabor verduras braseadas sin gluten",
        "Snack Maniac (Dia) — Palitos de patata sin gluten",
        "Snack Maniac (Dia) — Patatas fritas al punto de sal sin gluten",
      ],
      "Desayuno y cereales": [
        "Nestlé (Dia) — Corn Flakes sin gluten",
        "Dia Sin Gluten — Cereales sin gluten (gama propia)",
        "Gran Dia — Copos de avena 100% integral sin gluten",
        "Esgir (en Dia) — Salvado de avena sin gluten",
      ],
      "Salsas y condimentos": [
        "Dia Selección Mundial — Salsa de soja sin gluten",
        "Dia Salseo — Ketchup sin gluten",
        "Dia Salseo — Mayonesa sin gluten y sin lactosa",
        "Dia Salseo — Mostaza sin gluten",
      ],
      Congelados: [
        "Dia Al Punto — Lasaña boloñesa sin gluten",
        "Dr. Oetker Ristorante (Dia) — Pizza prosciutto sin gluten",
        "Dia Sin Gluten — Empanadillas sin gluten",
      ],
      Bebidas: [
        "Dia Ramblers — Cerveza especial sin gluten",
        "Dia — Horchata sin gluten",
        "Dia (Vegedia) — Bebida de chufa 0% azúcares, sin gluten y sin lactosa",
        "Dia Vegedia — Bebida de soja 0% azúcares sin gluten",
      ],
      "Dulces y postres": [
        "Dulce Noel Dia — Turrón crujiente de chocolate sin azúcares añadidos, sin gluten",
        "Dulce Noel Dia — Turrón de chocolate con leche y almendras sin gluten",
        "Dulce Noel Dia — Turrón de chocolate con leche crujiente clásico, sin gluten",
        "Galleteca (Dia Sin Gluten) — Galletas con pepitas de chocolate y sabor mantequilla, sin gluten",
        "Galleteca (Dia) — Galletas sabor mantequilla sin gluten",
        "Galleteca (Dia) — Galletas María con chocolate sin gluten",
        "Dulce Noel Dia — Turrón de Jijona sin gluten y sin lactosa",
        "Dulce Noel Dia — Turrón de Alicante sin gluten",
        "Dulce Noel Dia — Turrón crujiente de chocolate negro sin gluten",
      ],
      "Lácteos y alternativas": [
        "Dia — Bífidus con piña y coco doble 0%, sin gluten",
        "Dia — Bífidus con nueces y cereales doble 0%, sin gluten",
        "Dia — Bífidus con fresa doble 0%, sin gluten",
        "Dia Láctea — Yogur sabor fresa sin gluten",
      ],
      "Legumbres y conservas": [
        "Dia — Lentejas cocidas sin gluten",
        "Dia — Garbanzos cocidos sin gluten",
        "Dia — Alubias blancas extra sin gluten",
        "Dia — Lentejas con chorizo sin gluten",
        "Vegecampo de Dia — Lentejas pardinas sin gluten",
        "Vegecampo de Dia — Alubias blancas bajas en sal sin gluten",
      ],
      "Harinas y repostería": [
        "El Molino de Dia — Harina de garbanzo sin gluten",
        "Dia Delimagic — Preparado para hornear en polvo sin gluten",
        "Dr. Oetker (en Dia) — Preparado para bizcocho sin gluten",
      ],
      "Alimentación infantil": [
        "Hero Baby (Dia) — Potitos de frutas ecológicos sin gluten",
        "Nestlé (Dia) — Puré de 7 frutas sin gluten",
        "Smileat / Be Plus (Dia) — Potitos y tarritos sin gluten, sin lactosa",
        "Nestlé (Dia) — Puré de hortalizas y ternera sin gluten",
        "Hero Baby (Dia) — Puré de manzana, plátano y yogur ecológico sin gluten",
        "Smileat (Dia) — Puré de ternera con verduras ecológico sin gluten",
        "Smileat (Dia) — Puré de verduras y pavo ecológico sin gluten",
      ],
    },
  },
  aldi: {
    label: "Aldi",
    categorias: {
      "Panadería y bollería": [
        "Aldi — Pan de molde sin gluten",
        "GutBio — Pan sin gluten (base teff)",
        "Aldi — Bagels sin gluten",
        "Aldi — Panecillos sin gluten",
      ],
      "Pasta y arroz": [
        "GutBio — Fusilli de arroz integral y teff",
        "GutBio — Pasta de lentejas",
        "GutBio — Pasta de legumbres variadas",
        "GutBio — Espaguetis de edamame ecológicos",
        "GutBio — Sedanini de lentejas rojas y remolacha",
      ],
      "Snacks y aperitivos": [
        "Aldi — Patatas fritas sin gluten sabor entrecot con setas",
        "Aldi — Patatas fritas sin gluten sabor sobrasada ibérica",
        "AURADA — Tortitas de maíz",
        "AURADA — Tortitas de arroz",
        "AURADA — Tortitas de maíz con chocolate negro",
      ],
      "Desayuno y cereales": [
        "Golden Bridge — Copos de avena integral certificados sin gluten",
        "Golden Bridge — Copos de avena integral XXL",
        "Golden Bridge — Avena Rings",
      ],
      "Salsas y condimentos": [
        "La Villa — Kétchup sin gluten",
        "La Villa — Mayonesa sin gluten",
        "La Villa — Mostaza sin gluten",
        "La Villa — Salsa barbacoa sin gluten",
      ],
      Congelados: [
        "Aldi — Pizza de jamón y queso sin gluten",
        "Aldi — Gama de pizzas sin gluten (16 referencias)",
        "Aldi — Empanadillas sin gluten",
        "Aldi — Chicken fingers / croquetas de pollo empanadas sin gluten",
      ],
      Bebidas: [
        "Karlsquell — Cerveza Especial Sin Gluten (Bio)",
        "Karlsquell — Cerveza sin alcohol sin gluten",
        "Maternus — Cerveza Rubia Sin Gluten",
        "Milsani — Horchata sin gluten",
      ],
      "Dulces y postres": [
        "Biscotto — Galletas Chocobrownie sin gluten",
        "Biscotto — Galletas con pepitas de chocolate sin gluten",
        "GutBio — Galletas de avena sin gluten sabor limón y canela",
        "GutBio — Galletas de avena sin gluten sabor naranja, cúrcuma y jengibre",
        "Choceur — Bombones de chocolate sin gluten",
        "Flor de Navidad — Turrón sin gluten (blando Jijona y yema tostada)",
        "Flor de Navidad — Turrón blando de cacahuete sin gluten",
      ],
      "Lácteos y alternativas": [
        "GutBio — Bebida de avena ecológica sin gluten",
        "GutBio — Bebida de soja ecológica sin gluten",
        "GutBio — Bebida de arroz ecológica sin gluten",
        "GutBio — Bebida de almendra sin gluten",
        "GutBio — Bebida de avena 0% azúcares con vitaminas sin gluten",
        "GutBio — Bebida de avena barista sin azúcares ni lactosa, sin gluten",
      ],
      "Legumbres y conservas": [
        "GutBio — Garbanzos y alubias extra cocidos ecológicos",
        "GutBio — Lentejas y alubias rojas extra cocidas ecológicas",
        "GutBio — Plato de alubias, lentejas con verduras y garbanzos con espinacas",
      ],
      "Harinas y repostería": [
        "Aldi — Preparado para pan sin gluten (mezcla + levadura)",
        "Aldi — Harina de arroz sin gluten",
        "Aldi — Levadura de panadería/repostería sin gluten",
      ],
    },
  },
  consum: {
    label: "Consum",
    categorias: {
      "Panadería y bollería": [
        "Consum — Hogaza sin gluten",
        "Consum — Baguette sin gluten",
        "Consum — Baguettina sin gluten (congelada)",
        "Consum — Tostadas sin gluten integrales",
        "Consum — Pan de molde sin gluten cereales y semillas",
        "Consum — Bollo rústico sin gluten",
        "Consum — Bollo sin gluten (congelado)",
        "Consum — Pan de molde clásico sin gluten",
        "Consum — Pan tostado / tostas sin gluten",
      ],
      "Pasta y arroz": ["Consum — Spaghetti sin gluten", "Consum — Fideos sin gluten", "Consum — Tallarines de arroz"],
      "Snacks y aperitivos": [
        "Consum — Tortitas de maíz sin gluten",
        "Consum — Tortillas de maíz sin gluten",
        "Consum — Crackers sin gluten",
      ],
      "Desayuno y cereales": [
        "Consum — Cereales Choco Zero sin gluten y sin azúcares",
        "Consum — Cereales rellenos de leche sin gluten",
        "Consum — Cereales rellenos de choco sin gluten",
        "Consum — Corn Flakes Classic sin azúcar y sin gluten",
        "Consum — Arroz inflado choco sin gluten",
      ],
      "Salsas y condimentos": ["Consum — Tomate frito sin gluten", "Consum — Salsa de soja baja en sal y sin gluten"],
      Congelados: [
        "Ristorante (Dr. Oetker, en Consum) — Pizza Mozzarella sin gluten",
        "Ristorante — Pizza Prosciutto sin gluten y sin lactosa",
        "Ristorante — Pizza Jamón y Queso sin gluten y sin lactosa",
        "Consum — Nuggets de pollo sin gluten y sin lactosa",
        "Consum — Base de pizza sin gluten",
        "Consum — Cono nata-chocolate x4 sin gluten y sin lactosa",
        "Consum — Masa/base de pizza sin gluten (formato adicional)",
        "Consum — Cono de golosinas sin gluten",
      ],
      Bebidas: [
        "Consum — Cerveza sin gluten",
        "Damm — Daura, cerveza sin gluten",
        "Consum — Cerveza Celíacos (0,0)",
        "Damm — Daura, cerveza sin gluten en lata",
      ],
      "Dulces y postres": [
        "Consum — Magdalenas artesanas sin gluten",
        "Consum — Plumcake sin gluten con pepitas de chocolate",
        "Consum — Muffin de chocolate sin gluten",
        "Consum — Bizcocho sin gluten con pepitas de chocolate",
        "Consum — Galleta María sin gluten",
        "Consum — Bombones surtidos sin gluten",
        "Consum — Sandwich de chocolate sin gluten",
        "Consum — Galletas sandwich crema Hookies sin gluten",
        "Consum — Mini galletas Hookies Sharkies sin gluten",
        "Consum — Membrillo artesano natural sin gluten",
      ],
      "Lácteos y alternativas": [
        "Consum — Queso Pell Florida de leche de cabra pasteurizada, sin gluten",
        "Consum — Queso fresco Servilleta de leche de vaca pasteurizada, sin gluten",
        "Consum — Queso de oveja pasta blanda, sin gluten",
      ],
      "Legumbres y conservas": ["Consum — Garbanzo cocido 100% nacional sin gluten"],
      "Harinas y repostería": [
        "Consum — Harina mix sin gluten multiusos",
        "Consum — Pan rallado sin gluten",
        "Consum — Rebozado crujiente sin gluten",
      ],
      "Alimentación infantil": ["Consum — Crema de arroz sin gluten (papilla)", "Consum — Crema de arroz sin gluten y sin azúcar (papilla)"],
    },
  },
};

const recetas = [
  {
    icon: "🍳",
    title: "Tortilla de patatas clásica",
    meta: "~320 kcal · 35 min",
    ingredientes: ["4 patatas medianas", "5 huevos", "1 cebolla", "Aceite de oliva virgen extra", "Sal"],
    pasos: [
      "Pelar las patatas y cortarlas en láminas finas (2-3 mm); cortar la cebolla en juliana fina.",
      "Calentar abundante aceite de oliva en una sartén amplia a fuego medio-bajo.",
      "Añadir las patatas y la cebolla, salar ligeramente y confitar 20-25 minutos, removiendo de vez en cuando, hasta que estén blandas sin dorarse.",
      "Escurrir bien el aceite con un colador, reservando un par de cucharadas para cuajar.",
      "Batir los huevos en un bol amplio, mezclar con las patatas y la cebolla templadas y dejar reposar 5 minutos.",
      "Calentar el aceite reservado en una sartén antiadherente de 20-22 cm y verter la mezcla, repartiendo bien.",
      "Cuajar a fuego medio 2-3 minutos, dar la vuelta con ayuda de un plato y cuajar otros 2-3 minutos por el otro lado.",
      "Dejar reposar unos minutos antes de cortar y servir.",
    ],
  },
  {
    icon: "🍗",
    title: "Pollo al horno con verduras",
    meta: "~410 kcal · 45 min",
    ingredientes: ["4 muslos de pollo", "1 calabacín", "1 pimiento rojo", "2 patatas", "Aceite de oliva y romero"],
    pasos: [
      "Precalentar el horno a 200 °C con calor arriba y abajo.",
      "Lavar y cortar el calabacín, el pimiento y las patatas en trozos regulares de tamaño similar.",
      "Salpimentar los muslos de pollo y las verduras.",
      "Colocar todo en una bandeja de horno amplia, sin amontonar, para que se doren en vez de cocerse al vapor.",
      "Regar con un buen chorro de aceite de oliva y espolvorear el romero.",
      "Hornear 25 minutos, sacar y dar la vuelta al pollo, removiendo las verduras.",
      "Hornear 15-20 minutos más, hasta que el pollo esté dorado y las verduras tiernas.",
      "Dejar reposar 5 minutos fuera del horno antes de servir.",
    ],
  },
  {
    icon: "🍤",
    title: "Arroz con verduras y gambas",
    meta: "~380 kcal · 30 min",
    ingredientes: ["300 g de arroz", "200 g de gambas peladas", "1 pimiento verde", "Guisantes", "Caldo de verduras sin gluten"],
    pasos: [
      "Picar el ajo y el pimiento verde en trozos pequeños.",
      "Calentar aceite de oliva en una cazuela ancha y sofreír el ajo y el pimiento 4-5 minutos, hasta que estén blandos.",
      "Añadir el arroz y remover 1-2 minutos para que se impregne del sofrito.",
      "Verter el caldo de verduras caliente (el doble de volumen que el arroz) y llevar a ebullición.",
      "Bajar el fuego a medio-bajo, añadir los guisantes y cocer 15 minutos sin remover demasiado.",
      "Incorporar las gambas peladas y cocer 3 minutos más, hasta que cambien de color.",
      "Apagar el fuego, tapar y dejar reposar 2-3 minutos antes de servir.",
    ],
  },
  {
    icon: "🥑",
    title: "Ensalada de quinoa y aguacate",
    meta: "~340 kcal · 20 min",
    ingredientes: ["150 g de quinoa", "1 aguacate", "Tomates cherry", "Pepino", "Limón y aceite de oliva"],
    pasos: [
      "Enjuagar la quinoa con un colador fino bajo el grifo para quitar el sabor amargo de la saponina.",
      "Cocerla en agua con una pizca de sal (1 parte de quinoa por 2 de agua) 12-15 minutos, hasta que los granos se abran.",
      "Escurrir y dejar enfriar completamente extendida en una bandeja, para que no quede pastosa.",
      "Cortar el aguacate en dados, los tomates cherry por la mitad y el pepino en cubos pequeños.",
      "Mezclar la quinoa fría con las verduras en un bol grande.",
      "Preparar la vinagreta batiendo el zumo de limón, el aceite de oliva y una pizca de sal.",
      "Aliñar justo antes de servir para que el aguacate no se oxide.",
    ],
  },
  {
    icon: "🎃",
    title: "Crema de calabaza",
    meta: "~210 kcal · 30 min",
    ingredientes: ["500 g de calabaza", "1 cebolla", "1 zanahoria", "Caldo de verduras sin gluten", "Un chorrito de nata ligera (opcional)"],
    pasos: [
      "Pelar y trocear la calabaza, la cebolla y la zanahoria en trozos medianos.",
      "Calentar un chorro de aceite de oliva en una olla y pochar la cebolla y la zanahoria a fuego medio-bajo 8-10 minutos.",
      "Añadir la calabaza troceada y rehogar 2-3 minutos más.",
      "Cubrir con el caldo de verduras caliente (que cubra ligeramente las verduras) y salar.",
      "Cocer a fuego medio 20-25 minutos, hasta que todo esté muy tierno al pincharlo con un tenedor.",
      "Triturar con batidora hasta conseguir una crema fina, añadiendo más caldo si queda demasiado espesa.",
      "Añadir un chorrito de nata ligera si se desea, remover y servir bien caliente.",
    ],
  },
  {
    icon: "🐟",
    title: "Salmón a la plancha con puré de boniato",
    meta: "~430 kcal · 30 min",
    ingredientes: ["2 lomos de salmón", "2 boniatos", "Leche o bebida vegetal", "Aceite de oliva", "Eneldo"],
    pasos: [
      "Pelar los boniatos y cortarlos en trozos medianos.",
      "Cocerlos en agua con sal 15-18 minutos, hasta que estén muy tiernos al pincharlos.",
      "Escurrir y triturar con un poco de leche caliente y un chorrito de aceite hasta obtener un puré fino; salpimentar.",
      "Secar bien los lomos de salmón con papel de cocina y salpimentar.",
      "Calentar una plancha o sartén antiadherente con un poco de aceite a fuego fuerte.",
      "Marcar el salmón por el lado de la piel 3-4 minutos, hasta que esté crujiente, y dar la vuelta.",
      "Cocinar 2-3 minutos más por el otro lado, según el grosor, hasta que quede jugoso por dentro.",
      "Servir el salmón sobre una base de puré de boniato y espolvorear eneldo fresco picado.",
    ],
  },
  {
    icon: "🍅",
    title: "Gazpacho andaluz",
    meta: "~150 kcal · 15 min",
    ingredientes: ["1 kg de tomates maduros", "1 pepino", "1 pimiento verde", "1 diente de ajo", "Aceite de oliva, vinagre y sal"],
    pasos: [
      "Lavar los tomates y quitarles el pedúnculo; trocear junto con el pepino, el pimiento verde y el ajo.",
      "Colocar todas las verduras en el vaso de la batidora junto con el aceite de oliva, el vinagre y la sal.",
      "Triturar a máxima potencia 2-3 minutos, hasta obtener una mezcla completamente fina.",
      "Probar y rectificar de sal, vinagre o aceite al gusto.",
      "Colar con un colador fino o chino si se prefiere una textura sin pieles ni pepitas.",
      "Enfriar en la nevera un mínimo de 1-2 horas antes de servir bien frío.",
      "Servir con dados de pepino, pimiento y tomate picado por encima si se desea.",
    ],
  },
  {
    icon: "🍖",
    title: "Albóndigas en salsa de tomate",
    meta: "~450 kcal · 50 min",
    ingredientes: ["500 g de carne picada", "1 huevo", "Pan rallado sin gluten", "Tomate triturado", "Ajo, perejil y aceite de oliva"],
    pasos: [
      "Picar finamente el ajo y el perejil.",
      "En un bol grande, mezclar la carne picada con el huevo, el pan rallado sin gluten, el ajo y el perejil; salpimentar y amasar bien.",
      "Dejar reposar la masa 10 minutos en la nevera para que sea más fácil de formar.",
      "Formar bolas de tamaño similar con las manos humedecidas.",
      "Calentar aceite de oliva en una sartén y dorar las albóndigas por todos los lados a fuego medio-alto.",
      "Retirar y reservar; en la misma sartén, añadir el tomate triturado y una pizca de sal.",
      "Incorporar de nuevo las albóndigas a la salsa y cocer a fuego lento 20-25 minutos, removiendo de vez en cuando.",
      "Servir calientes, con un poco de perejil picado por encima.",
    ],
  },
  {
    icon: "🥙",
    title: "Poke bowl de atún",
    meta: "~420 kcal · 25 min",
    ingredientes: ["200 g de atún fresco", "Arroz cocido", "Edamame", "Aguacate y zanahoria", "Salsa de soja sin gluten (tamari)"],
    pasos: [
      "Cortar el atún fresco en dados de 1-2 cm.",
      "Marinar el atún con la salsa de soja sin gluten (tamari) durante 10-15 minutos en la nevera.",
      "Cocer el arroz según las instrucciones del paquete y dejar enfriar ligeramente (templado, no caliente).",
      "Cortar el aguacate en láminas y la zanahoria en tiras finas o rallada.",
      "Descongelar o cocer el edamame según indique el envase.",
      "Montar el bowl colocando el arroz como base y distribuyendo el atún, el aguacate, la zanahoria y el edamame en secciones.",
      "Terminar con un poco de la marinada de tamari por encima y semillas de sésamo si se desea.",
    ],
  },
  {
    icon: "🥞",
    title: "Crepes de trigo sarraceno con fruta",
    meta: "~280 kcal · 20 min",
    ingredientes: [
      "150 g de harina de trigo sarraceno (naturalmente sin gluten)",
      "2 huevos",
      "250 ml de leche o bebida vegetal",
      "Fruta fresca al gusto",
      "Una pizca de sal",
    ],
    pasos: [
      "Tamizar la harina de trigo sarraceno en un bol grande para evitar grumos.",
      "Batir los huevos aparte y añadirlos a la harina poco a poco, alternando con la leche, hasta conseguir una masa homogénea.",
      "Añadir una pizca de sal y dejar reposar la masa 15-20 minutos a temperatura ambiente.",
      "Calentar una sartén antiadherente a fuego medio y engrasar ligeramente con un poco de aceite.",
      "Verter un cucharón de masa y repartir girando la sartén para que quede una capa fina y uniforme.",
      "Cocinar 1-2 minutos hasta que los bordes se despeguen, dar la vuelta y cocinar 1 minuto más por el otro lado.",
      "Repetir con el resto de la masa, apilando los crepes en un plato.",
      "Rellenar o cubrir con fruta fresca troceada al gusto y servir templados.",
    ],
  },
  {
    icon: "🥣",
    title: "Porridge de avena con frutos rojos",
    meta: "~320 kcal · 10 min",
    ingredientes: [
      "80 g de copos de avena certificados sin gluten",
      "250 ml de leche o bebida vegetal",
      "Un puñado de frutos rojos (fresas, arándanos, frambuesas)",
      "1 cucharadita de miel",
      "Canela al gusto",
    ],
    pasos: [
      "Verter la avena y la leche en un cazo pequeño.",
      "Calentar a fuego medio, removiendo con frecuencia para que no se pegue.",
      "Cocer 5-7 minutos, hasta que la avena haya absorbido el líquido y tenga una textura cremosa.",
      "Retirar del fuego y dejar templar 1-2 minutos.",
      "Servir en un bol, añadir los frutos rojos por encima, un chorrito de miel y espolvorear canela.",
    ],
  },
  {
    icon: "🥔",
    title: "Vichyssoise (crema fría de puerro y patata)",
    meta: "~230 kcal · 40 min + enfriado",
    ingredientes: ["3 puerros (solo la parte blanca)", "2 patatas medianas", "1 cebolla pequeña", "Caldo de verduras sin gluten", "Nata líquida o bebida vegetal"],
    pasos: [
      "Lavar bien los puerros entre las capas y cortarlos en rodajas finas, junto con la cebolla.",
      "Pelar y trocear las patatas en dados medianos.",
      "Calentar un chorro de aceite de oliva en una olla y pochar el puerro y la cebolla a fuego bajo 10 minutos, sin que cojan color.",
      "Añadir las patatas y el caldo de verduras (que cubra los ingredientes) y salar.",
      "Cocer a fuego medio 20-25 minutos, hasta que la patata esté muy tierna.",
      "Triturar todo hasta obtener una crema fina; añadir un chorro de nata o bebida vegetal y volver a triturar.",
      "Dejar enfriar a temperatura ambiente y luego refrigerar al menos 2 horas.",
      "Servir bien fría, con cebollino picado por encima si se desea.",
    ],
  },
  {
    icon: "🍖",
    title: "Solomillo de cerdo con salsa de mostaza",
    meta: "~410 kcal · 35 min",
    ingredientes: ["1 solomillo de cerdo (~500 g)", "2 cucharadas de mostaza sin gluten", "200 ml de nata para cocinar", "1 cebolla", "Aceite de oliva"],
    pasos: [
      "Salpimentar el solomillo y cortarlo en medallones de 2-3 cm.",
      "Picar la cebolla finamente.",
      "Calentar aceite de oliva en una sartén a fuego fuerte y dorar los medallones 2 minutos por cada lado; retirar y reservar.",
      "En la misma sartén, bajar el fuego y pochar la cebolla 5-6 minutos, hasta que esté transparente.",
      "Añadir la nata y la mostaza, remover bien y cocinar 3-4 minutos a fuego medio hasta que espese ligeramente.",
      "Incorporar de nuevo los medallones a la salsa y cocinar 4-5 minutos más, hasta que estén hechos por dentro.",
      "Probar y rectificar de sal si es necesario.",
      "Servir caliente con la salsa por encima.",
    ],
  },
  {
    icon: "🐠",
    title: "Merluza en salsa verde",
    meta: "~280 kcal · 30 min",
    ingredientes: ["4 lomos de merluza", "3 dientes de ajo", "Perejil fresco", "200 ml de caldo de pescado sin gluten", "Aceite de oliva y 1 cucharada de harina de arroz (opcional)"],
    pasos: [
      "Salar los lomos de merluza y reservar.",
      "Picar el ajo y el perejil finamente.",
      "Calentar aceite de oliva en una cazuela amplia y dorar el ajo a fuego bajo, sin que se queme.",
      "Si se desea espesar la salsa, añadir la harina de arroz y remover 1 minuto.",
      "Verter el caldo de pescado poco a poco, removiendo para que no se formen grumos.",
      "Añadir el perejil picado y llevar a un ligero hervor.",
      "Colocar los lomos de merluza en la cazuela, con la piel hacia abajo, y cocinar a fuego medio-bajo 8-10 minutos, moviendo la cazuela de vez en cuando en vez de remover.",
      "Servir la merluza con la salsa verde por encima.",
    ],
  },
  {
    icon: "🍛",
    title: "Curry de garbanzos y espinacas",
    meta: "~360 kcal · 30 min",
    ingredientes: ["400 g de garbanzos cocidos sin gluten", "200 g de espinacas frescas", "1 cebolla", "400 ml de leche de coco", "2 cucharaditas de curry en polvo sin gluten", "1 diente de ajo"],
    pasos: [
      "Picar la cebolla y el ajo finamente.",
      "Calentar aceite de oliva en una sartén honda y sofreír la cebolla y el ajo a fuego medio 5 minutos.",
      "Añadir el curry en polvo y remover 1 minuto para que suelte aroma.",
      "Incorporar los garbanzos escurridos y remover para que se impregnen de las especias.",
      "Verter la leche de coco y cocinar a fuego medio 10-12 minutos, removiendo de vez en cuando.",
      "Añadir las espinacas y cocinar 2-3 minutos más, hasta que se ablanden.",
      "Salpimentar al gusto y servir caliente, con arroz basmati como acompañamiento si se desea.",
    ],
  },
  {
    icon: "🍝",
    title: "Carbonara sin gluten",
    meta: "~520 kcal · 20 min",
    ingredientes: ["350 g de pasta sin gluten (espagueti)", "150 g de panceta o bacon", "3 huevos", "50 g de queso parmesano rallado", "Pimienta negra"],
    pasos: [
      "Poner una olla grande con agua y sal a hervir para la pasta.",
      "Cortar la panceta en tiras o dados pequeños.",
      "Cocer la pasta sin gluten según las instrucciones del paquete (suele necesitar 1-2 minutos menos que la pasta normal).",
      "Mientras tanto, dorar la panceta en una sartén grande a fuego medio, sin aceite adicional, hasta que esté crujiente.",
      "En un bol, batir los huevos con el queso parmesano y una buena cantidad de pimienta negra molida.",
      "Escurrir la pasta reservando un cazo del agua de cocción.",
      "Añadir la pasta caliente a la sartén con la panceta y retirar del fuego.",
      "Incorporar la mezcla de huevo y queso, removiendo rápido sin volver a poner al fuego directo.",
      "Añadir un poco del agua de cocción reservada si queda demasiado espesa, y servir inmediatamente.",
    ],
  },
  {
    icon: "🍫",
    title: "Brownie sin gluten",
    meta: "~290 kcal por ración · 40 min",
    ingredientes: ["200 g de chocolate negro sin gluten", "150 g de mantequilla", "3 huevos", "180 g de azúcar", "80 g de harina de arroz o mezcla panificable sin gluten", "Nueces troceadas (opcional)"],
    pasos: [
      "Precalentar el horno a 180 °C y forrar un molde rectangular con papel de horno.",
      "Trocear el chocolate y derretirlo junto con la mantequilla al baño maría o en el microondas en golpes cortos.",
      "Dejar templar la mezcla de chocolate unos minutos.",
      "Batir los huevos con el azúcar hasta que blanqueen y dupliquen su volumen.",
      "Incorporar el chocolate derretido a los huevos, mezclando con movimientos envolventes.",
      "Tamizar la harina sin gluten sobre la mezcla y añadir con cuidado, sin batir en exceso.",
      "Añadir las nueces si se desea y verter la masa en el molde.",
      "Hornear 20-25 minutos: el interior debe quedar húmedo y ligeramente poco hecho.",
      "Dejar enfriar completamente en el molde antes de cortar en cuadrados.",
    ],
  },
];

// Planes de dieta de 4 semanas (28 días), en 3 niveles calóricos (1500/2000/2500
// kcal/día). Cada nivel se construye combinando 5 "pools" de 10 opciones de comida
// (desayuno, media mañana, comida, merienda, cena) con un desfase distinto por tipo
// de comida, para que el combo completo de cada día varíe a lo largo del mes aunque
// algún componente suelto se repita cada 10 días (igual que en un plan real).
const comidasPool = {
  1500: {
    desayuno: [
      "Tortilla de 2 huevos con espinacas y una tostada de pan sin gluten (~300 kcal).",
      "Porridge de 40 g de avena certificada sin gluten con leche y plátano (~300 kcal).",
      "Yogur griego con granola sin gluten y arándanos (~290 kcal).",
      "Tostada de pan sin gluten con aguacate y huevo poché (~300 kcal).",
      "Batido de proteína con leche, plátano y avena certificada sin gluten (~290 kcal).",
      "Requesón con fresas y un puñado de almendras (~280 kcal).",
      "Tostada de pan sin gluten con tomate rallado, aceite de oliva y jamón serrano (~300 kcal).",
      "Crepe de trigo sarraceno (naturalmente sin gluten) con fruta fresca (~290 kcal).",
      "Cereales de maíz sin gluten con leche y fresas (~290 kcal).",
      "Huevos revueltos con boniato asado y aguacate (~300 kcal).",
    ],
    mediaManana: [
      "Una manzana y un puñado de nueces (~140 kcal).",
      "Yogur natural sin azúcar con canela (~120 kcal).",
      "Hummus con bastones de zanahoria y pepino (~140 kcal).",
      "Batido de frutos rojos con leche (~130 kcal).",
      "Requesón con una pieza de fruta (~130 kcal).",
      "Dos tortitas de arroz con aguacate (~140 kcal).",
      "Un puñado de uvas con queso curado (~140 kcal).",
      "Media ración de batido de proteína con agua (~120 kcal).",
      "Infusión con un puñado de orejones (~130 kcal).",
      "Media barrita casera de dátiles y frutos secos (~140 kcal).",
    ],
    comida: [
      "Pechuga de pollo a la plancha con arroz basmati y brócoli (~420 kcal).",
      "Salmón al horno con boniato asado y ensalada verde (~430 kcal).",
      "Lentejas estofadas con verduras (~420 kcal).",
      "Pasta sin gluten con pollo y verduras salteadas (~430 kcal).",
      "Merluza a la plancha con patata cocida y ensalada (~420 kcal).",
      "Poke bowl de atún con arroz, edamame y aguacate (~430 kcal).",
      "Curry de garbanzos y espinacas con arroz (~430 kcal).",
      "Solomillo de cerdo a la plancha con verduras salteadas (~420 kcal).",
      "Ensalada de quinoa con atún, aguacate y tomate (~420 kcal).",
      "Albóndigas en salsa de tomate con arroz (~430 kcal).",
    ],
    merienda: [
      "Yogur natural con nueces (~140 kcal).",
      "Media tostada de pan sin gluten con aguacate (~140 kcal).",
      "Queso fresco batido con fresas (~130 kcal).",
      "Batido de cacao puro con leche (~140 kcal).",
      "Un puñado de almendras y pasas (~140 kcal).",
      "Tortitas de maíz sin gluten con jamón cocido (~140 kcal).",
      "Hummus con tortitas de arroz (~140 kcal).",
      "Batido de proteína con agua y fresas (~140 kcal).",
      "Compota de manzana sin azúcar añadido con nueces (~140 kcal).",
      "Barrita de cereales sin gluten (~140 kcal).",
    ],
    cena: [
      "Tortilla de patatas (2 huevos) con ensalada verde (~420 kcal).",
      "Pescado blanco al vapor con verduras (~420 kcal).",
      "Crema de calabaza con un huevo duro (~420 kcal).",
      "Ensalada de pollo, rúcula, tomate y queso feta (~420 kcal).",
      "Revuelto de huevo con gambas y espárragos (~420 kcal).",
      "Tofu salteado con verduras y salsa de soja sin gluten (~420 kcal).",
      "Merluza en salsa verde con espárragos (~420 kcal).",
      "Pechuga de pavo a la plancha con calabacín y zanahoria (~420 kcal).",
      "Vichyssoise con una tostada de pan sin gluten (~420 kcal).",
      "Gazpacho andaluz con tortilla francesa de 2 huevos (~420 kcal).",
    ],
  },
  1750: {
    desayuno: [
      "Tortilla de 3 huevos con espinacas y una tostada de pan sin gluten (~350 kcal).",
      "Porridge de 50 g de avena certificada sin gluten con leche y plátano (~350 kcal).",
      "Yogur griego con granola sin gluten y arándanos (~350 kcal).",
      "Dos tostadas de pan sin gluten con aguacate y huevo poché (~360 kcal).",
      "Batido de proteína con leche, plátano y avena certificada sin gluten (~350 kcal).",
      "Requesón con fresas y un puñado de almendras (~340 kcal).",
      "Dos tostadas de pan sin gluten con tomate rallado, aceite de oliva y jamón serrano (~360 kcal).",
      "Dos crepes de trigo sarraceno con fruta fresca (~350 kcal).",
      "Cereales de maíz sin gluten con leche y fresas (~350 kcal).",
      "Tres huevos revueltos con boniato asado y aguacate (~350 kcal).",
    ],
    mediaManana: [
      "Una manzana y un puñado de nueces (~170 kcal).",
      "Yogur griego natural con canela (~160 kcal).",
      "Hummus con bastones de zanahoria y pepino (~170 kcal).",
      "Batido de frutos rojos con leche (~170 kcal).",
      "Requesón con una pieza de fruta (~170 kcal).",
      "Tres tortitas de arroz con aguacate (~170 kcal).",
      "Un puñado de uvas con queso curado (~170 kcal).",
      "Batido de proteína con agua (~160 kcal).",
      "Infusión con un puñado de orejones (~170 kcal).",
      "Barrita casera de dátiles y frutos secos (~170 kcal).",
    ],
    comida: [
      "Pechuga de pollo a la plancha con arroz basmati, brócoli y aceite de oliva (~520 kcal).",
      "Salmón al horno con boniato asado, ensalada verde y aceite de oliva (~520 kcal).",
      "Lentejas estofadas con verduras y arroz (~520 kcal).",
      "Pasta sin gluten con pollo, verduras salteadas y queso parmesano (~520 kcal).",
      "Merluza a la plancha con patata cocida, ensalada y aceite de oliva (~520 kcal).",
      "Poke bowl de atún con arroz, edamame, aguacate y salsa de soja sin gluten (~520 kcal).",
      "Curry de garbanzos y espinacas con arroz y leche de coco (~520 kcal).",
      "Solomillo de cerdo a la plancha con verduras salteadas y arroz (~520 kcal).",
      "Ensalada de quinoa con atún, aguacate, tomate y huevo duro (~520 kcal).",
      "Albóndigas en salsa de tomate con arroz y ensalada (~520 kcal).",
    ],
    merienda: [
      "Yogur griego con nueces (~175 kcal).",
      "Tostada de pan sin gluten con aguacate (~175 kcal).",
      "Queso fresco batido con fresas (~170 kcal).",
      "Batido de cacao puro con leche y avena certificada (~175 kcal).",
      "Almendras y pasas (~175 kcal).",
      "Tortitas de maíz sin gluten con jamón cocido y tomate (~175 kcal).",
      "Hummus con tortitas de arroz y zanahoria (~175 kcal).",
      "Batido de proteína con leche y fresas (~175 kcal).",
      "Compota de manzana con nueces y canela (~175 kcal).",
      "Barrita de cereales sin gluten y una pieza de fruta (~175 kcal).",
    ],
    cena: [
      "Tortilla de patatas (3 huevos) con ensalada verde y pan sin gluten (~520 kcal).",
      "Pescado blanco al horno con verduras y patata (~520 kcal).",
      "Crema de calabaza con huevo duro y pan sin gluten (~520 kcal).",
      "Ensalada de pollo, rúcula, tomate, queso feta y nueces (~520 kcal).",
      "Revuelto de huevo con gambas, espárragos y pan sin gluten (~520 kcal).",
      "Tofu salteado con verduras, arroz y salsa de soja sin gluten (~520 kcal).",
      "Merluza en salsa verde con espárragos y patata (~520 kcal).",
      "Pechuga de pavo a la plancha con calabacín, zanahoria y arroz (~520 kcal).",
      "Vichyssoise con dos tostadas de pan sin gluten y jamón (~520 kcal).",
      "Gazpacho andaluz con tortilla francesa de 3 huevos y pan sin gluten (~520 kcal).",
    ],
  },
  2000: {
    desayuno: [
      "Tortilla de 3 huevos con espinacas y dos tostadas de pan sin gluten (~400 kcal).",
      "Porridge de 60 g de avena certificada sin gluten con leche, plátano y nueces (~400 kcal).",
      "Yogur griego con granola sin gluten, plátano y miel (~400 kcal).",
      "Dos tostadas de pan sin gluten con aguacate y huevo poché (~410 kcal).",
      "Batido de proteína con leche entera, plátano, avena certificada y crema de cacahuete (~400 kcal).",
      "Requesón con fresas, plátano y almendras (~390 kcal).",
      "Dos tostadas de pan sin gluten con tomate rallado, aceite de oliva y jamón serrano (~410 kcal).",
      "Dos crepes de trigo sarraceno con fruta fresca y yogur (~400 kcal).",
      "Cereales de maíz sin gluten con leche entera, plátano y nueces (~400 kcal).",
      "Tres huevos revueltos con boniato asado, aguacate y pan sin gluten (~410 kcal).",
    ],
    mediaManana: [
      "Una manzana y un puñado grande de nueces (~200 kcal).",
      "Yogur griego natural con un puñado de arándanos (~190 kcal).",
      "Hummus con bastones de zanahoria, pepino y pimiento (~200 kcal).",
      "Batido de frutos rojos con leche y avena certificada (~200 kcal).",
      "Requesón con fruta y un puñado de almendras (~200 kcal).",
      "Tres tortitas de arroz con aguacate y tomate (~200 kcal).",
      "Uvas con queso curado y nueces (~200 kcal).",
      "Batido de proteína con leche (~190 kcal).",
      "Infusión con orejones y almendras (~200 kcal).",
      "Barrita casera de dátiles y frutos secos (~200 kcal).",
    ],
    comida: [
      "Pechuga de pollo a la plancha con arroz basmati, brócoli y aceite de oliva (~600 kcal).",
      "Salmón al horno con boniato asado, ensalada verde y aceite de oliva (~600 kcal).",
      "Lentejas estofadas con verduras y arroz (~600 kcal).",
      "Pasta sin gluten con pollo, verduras salteadas y queso parmesano (~600 kcal).",
      "Merluza a la plancha con patata cocida, ensalada y aceite de oliva (~600 kcal).",
      "Poke bowl de atún con arroz, edamame, aguacate y salsa de soja sin gluten (~600 kcal).",
      "Curry de garbanzos y espinacas con arroz y leche de coco (~600 kcal).",
      "Solomillo de cerdo a la plancha con verduras salteadas y arroz (~600 kcal).",
      "Ensalada de quinoa con atún, aguacate, tomate y huevo duro (~600 kcal).",
      "Albóndigas en salsa de tomate con arroz y ensalada (~600 kcal).",
    ],
    merienda: [
      "Yogur griego con nueces y miel (~200 kcal).",
      "Tostada de pan sin gluten con aguacate (~200 kcal).",
      "Queso fresco batido con fresas y miel (~200 kcal).",
      "Batido de cacao puro con leche y avena certificada (~200 kcal).",
      "Almendras, pasas y una pieza de fruta (~200 kcal).",
      "Tortitas de maíz sin gluten con jamón cocido y tomate (~200 kcal).",
      "Hummus con tortitas de arroz y zanahoria (~200 kcal).",
      "Batido de proteína con leche y fresas (~200 kcal).",
      "Compota de manzana con nueces y canela (~200 kcal).",
      "Barrita de cereales sin gluten y una pieza de fruta (~200 kcal).",
    ],
    cena: [
      "Tortilla de patatas (3 huevos) con ensalada verde y pan sin gluten (~600 kcal).",
      "Pescado blanco al horno con verduras y patata (~600 kcal).",
      "Crema de calabaza con huevo duro y pan sin gluten (~600 kcal).",
      "Ensalada de pollo, rúcula, tomate, queso feta y nueces (~600 kcal).",
      "Revuelto de huevo con gambas, espárragos y pan sin gluten (~600 kcal).",
      "Tofu salteado con verduras, arroz y salsa de soja sin gluten (~600 kcal).",
      "Merluza en salsa verde con espárragos y patata (~600 kcal).",
      "Pechuga de pavo a la plancha con calabacín, zanahoria y arroz (~600 kcal).",
      "Vichyssoise con dos tostadas de pan sin gluten y jamón (~600 kcal).",
      "Gazpacho andaluz con tortilla francesa de 3 huevos y pan sin gluten (~600 kcal).",
    ],
  },
  2250: {
    desayuno: [
      "Tortilla de 3 huevos con espinacas y dos tostadas de pan sin gluten con aceite (~450 kcal).",
      "Porridge de 70 g de avena certificada sin gluten con leche, plátano y nueces (~450 kcal).",
      "Yogur griego con granola sin gluten, plátano y miel (~450 kcal).",
      "Dos tostadas de pan sin gluten con aguacate, huevo poché y queso fresco (~450 kcal).",
      "Batido de proteína con leche entera, plátano, avena certificada y crema de cacahuete (~450 kcal).",
      "Requesón con fresas, plátano y almendras (~440 kcal).",
      "Dos tostadas de pan sin gluten con tomate rallado, aceite de oliva, jamón serrano y queso fresco (~450 kcal).",
      "Dos crepes de trigo sarraceno con fruta fresca y yogur (~450 kcal).",
      "Cereales de maíz sin gluten con leche entera, plátano y nueces (~450 kcal).",
      "Tres huevos revueltos con boniato asado, aguacate y pan sin gluten (~450 kcal).",
    ],
    mediaManana: [
      "Una manzana y un puñado grande de nueces (~225 kcal).",
      "Yogur griego natural con un puñado de arándanos (~220 kcal).",
      "Hummus con bastones de zanahoria, pepino y pimiento (~225 kcal).",
      "Batido de frutos rojos con leche y avena certificada (~225 kcal).",
      "Requesón con fruta y un puñado de almendras (~225 kcal).",
      "Tres tortitas de arroz con aguacate y tomate (~225 kcal).",
      "Uvas con queso curado y nueces (~225 kcal).",
      "Batido de proteína con leche (~220 kcal).",
      "Infusión con orejones y almendras (~225 kcal).",
      "Barrita casera de dátiles y frutos secos con una pieza de fruta (~225 kcal).",
    ],
    comida: [
      "Pechuga de pollo a la plancha con arroz basmati, brócoli, aguacate y aceite de oliva (~670 kcal).",
      "Salmón al horno con boniato asado, quinoa y ensalada con aceite de oliva (~670 kcal).",
      "Lentejas estofadas con verduras, arroz y un huevo duro (~670 kcal).",
      "Pasta sin gluten con pollo, verduras salteadas, queso parmesano y aceite de oliva (~670 kcal).",
      "Merluza en salsa verde con patata cocida y ensalada con aceite de oliva (~670 kcal).",
      "Poke bowl grande de atún con arroz, edamame, aguacate y anacardos (~670 kcal).",
      "Curry de garbanzos y espinacas con arroz, leche de coco y anacardos (~670 kcal).",
      "Solomillo de cerdo con salsa de mostaza, verduras salteadas y arroz (~670 kcal).",
      "Ensalada de quinoa con atún, aguacate, tomate, huevo duro y aceite de oliva extra (~670 kcal).",
      "Albóndigas en salsa de tomate con arroz, ensalada y pan sin gluten (~670 kcal).",
    ],
    merienda: [
      "Yogur griego con nueces y miel (~225 kcal).",
      "Tostada de pan sin gluten con aguacate y huevo duro (~225 kcal).",
      "Queso fresco batido con fresas y miel (~225 kcal).",
      "Batido de cacao puro con leche entera, avena certificada y plátano (~225 kcal).",
      "Almendras, pasas y una pieza de fruta (~225 kcal).",
      "Tortitas de maíz sin gluten con jamón cocido, tomate y aguacate (~225 kcal).",
      "Hummus con tortitas de arroz, zanahoria y pepino (~225 kcal).",
      "Batido de proteína con leche, fresas y avena certificada (~225 kcal).",
      "Compota de manzana con nueces, canela y yogur (~225 kcal).",
      "Barrita de cereales sin gluten, una pieza de fruta y un puñado de nueces (~225 kcal).",
    ],
    cena: [
      "Tortilla de patatas (3 huevos) con ensalada verde, pan sin gluten y aceite de oliva extra (~670 kcal).",
      "Pescado blanco al horno con verduras, patata y aceite de oliva extra (~670 kcal).",
      "Crema de calabaza con huevo duro, pan sin gluten y jamón serrano (~670 kcal).",
      "Ensalada de pollo, rúcula, tomate, queso feta, nueces y aguacate (~670 kcal).",
      "Revuelto de huevo con gambas, espárragos, pan sin gluten y aguacate (~670 kcal).",
      "Tofu salteado con verduras, arroz, anacardos y salsa de soja sin gluten (~670 kcal).",
      "Merluza en salsa verde con espárragos, patata y pan sin gluten (~670 kcal).",
      "Pechuga de pavo a la plancha con calabacín, zanahoria, arroz y aceite de oliva extra (~670 kcal).",
      "Vichyssoise con dos tostadas de pan sin gluten, jamón y queso (~670 kcal).",
      "Gazpacho andaluz con tortilla francesa de 3 huevos, pan sin gluten y jamón (~670 kcal).",
    ],
  },
  2500: {
    desayuno: [
      "Tortilla de 3 huevos con espinacas, aguacate y dos tostadas de pan sin gluten (~500 kcal).",
      "Porridge de 80 g de avena certificada sin gluten con leche entera, plátano, nueces y miel (~500 kcal).",
      "Yogur griego con granola sin gluten, plátano, miel y frutos secos (~510 kcal).",
      "Dos tostadas de pan sin gluten con aguacate, huevo poché y salmón ahumado (~510 kcal).",
      "Batido de proteína con leche entera, plátano, avena certificada, crema de cacahuete y miel (~500 kcal).",
      "Requesón con fresas, plátano, almendras y miel (~500 kcal).",
      "Dos tostadas de pan sin gluten con tomate rallado, aceite de oliva, jamón serrano y queso fresco (~500 kcal).",
      "Dos crepes de trigo sarraceno con fruta fresca, yogur y miel (~500 kcal).",
      "Cereales de maíz sin gluten con leche entera, plátano, nueces y miel (~500 kcal).",
      "Tres huevos revueltos con boniato asado, aguacate, pan sin gluten y queso (~500 kcal).",
    ],
    mediaManana: [
      "Una manzana, un puñado grande de nueces y una cucharada de crema de cacahuete (~260 kcal).",
      "Yogur griego natural con arándanos y granola sin gluten (~260 kcal).",
      "Hummus con bastones de verduras y tortitas de maíz sin gluten (~260 kcal).",
      "Batido de frutos rojos con leche entera, avena certificada y miel (~260 kcal).",
      "Requesón con fruta, almendras y miel (~260 kcal).",
      "Tres tortitas de arroz con aguacate, tomate y huevo duro (~260 kcal).",
      "Uvas con queso curado, nueces y una tostada de pan sin gluten (~260 kcal).",
      "Batido de proteína con leche y plátano (~260 kcal).",
      "Infusión con orejones, almendras y nueces (~260 kcal).",
      "Barrita casera de dátiles y frutos secos con una pieza de fruta (~260 kcal).",
    ],
    comida: [
      "Pechuga de pollo a la plancha con arroz basmati, brócoli, aguacate y aceite de oliva (~750 kcal).",
      "Salmón al horno con boniato asado, quinoa y ensalada con aceite de oliva (~750 kcal).",
      "Lentejas estofadas con verduras, arroz y un huevo duro (~750 kcal).",
      "Pasta sin gluten con pollo, verduras salteadas, queso parmesano y aceite de oliva (~750 kcal).",
      "Merluza en salsa verde con patata cocida y ensalada con aceite de oliva (~750 kcal).",
      "Poke bowl grande de atún con arroz, edamame, aguacate y anacardos (~750 kcal).",
      "Curry de garbanzos y espinacas con arroz, leche de coco y anacardos (~750 kcal).",
      "Solomillo de cerdo con salsa de mostaza, verduras salteadas y arroz (~750 kcal).",
      "Ensalada de quinoa con atún, aguacate, tomate, huevo duro y aceite de oliva extra (~750 kcal).",
      "Albóndigas en salsa de tomate con arroz, ensalada y pan sin gluten (~750 kcal).",
    ],
    merienda: [
      "Yogur griego con nueces, miel y granola sin gluten (~260 kcal).",
      "Tostada de pan sin gluten con aguacate y huevo duro (~260 kcal).",
      "Queso fresco batido con fresas, miel y granola sin gluten (~260 kcal).",
      "Batido de cacao puro con leche entera, avena certificada y plátano (~260 kcal).",
      "Almendras, pasas, orejones y una pieza de fruta (~260 kcal).",
      "Tortitas de maíz sin gluten con jamón cocido, tomate y aguacate (~260 kcal).",
      "Hummus con tortitas de arroz, zanahoria y pepino (~260 kcal).",
      "Batido de proteína con leche, fresas y avena certificada (~260 kcal).",
      "Compota de manzana con nueces, canela y yogur (~260 kcal).",
      "Barrita de cereales sin gluten, una pieza de fruta y un puñado de nueces (~260 kcal).",
    ],
    cena: [
      "Tortilla de patatas (3 huevos) con ensalada verde, pan sin gluten y aceite de oliva extra (~750 kcal).",
      "Pescado blanco al horno con verduras, patata y aceite de oliva extra (~750 kcal).",
      "Crema de calabaza con huevo duro, pan sin gluten y jamón serrano (~750 kcal).",
      "Ensalada de pollo, rúcula, tomate, queso feta, nueces y aguacate (~750 kcal).",
      "Revuelto de huevo con gambas, espárragos, pan sin gluten y aguacate (~750 kcal).",
      "Tofu salteado con verduras, arroz, anacardos y salsa de soja sin gluten (~750 kcal).",
      "Merluza en salsa verde con espárragos, patata y pan sin gluten (~750 kcal).",
      "Pechuga de pavo a la plancha con calabacín, zanahoria, arroz y aceite de oliva extra (~750 kcal).",
      "Vichyssoise con dos tostadas de pan sin gluten, jamón y queso (~750 kcal).",
      "Gazpacho andaluz con tortilla francesa de 3 huevos, pan sin gluten y jamón (~750 kcal).",
    ],
  },
  2750: {
    desayuno: [
      "Tortilla de 4 huevos con espinacas, aguacate y dos tostadas de pan sin gluten (~550 kcal).",
      "Porridge de 90 g de avena certificada sin gluten con leche entera, plátano, nueces y miel (~550 kcal).",
      "Yogur griego con granola sin gluten, plátano, miel y frutos secos (~560 kcal).",
      "Dos tostadas de pan sin gluten con aguacate, huevo poché y salmón ahumado (~560 kcal).",
      "Batido de proteína con leche entera, plátano, avena certificada, crema de cacahuete y miel (~550 kcal).",
      "Requesón con fresas, plátano, almendras y miel (~550 kcal).",
      "Tres tostadas de pan sin gluten con tomate rallado, aceite de oliva, jamón serrano y queso fresco (~560 kcal).",
      "Tres crepes de trigo sarraceno con fruta fresca, yogur y miel (~560 kcal).",
      "Cereales de maíz sin gluten con leche entera, plátano, nueces y miel (~560 kcal).",
      "Tres huevos revueltos con boniato asado, aguacate, pan sin gluten y queso (~560 kcal).",
    ],
    mediaManana: [
      "Una manzana, un puñado grande de nueces y una cucharada de crema de cacahuete (~280 kcal).",
      "Yogur griego natural con arándanos y granola sin gluten (~280 kcal).",
      "Hummus con bastones de verduras y tortitas de maíz sin gluten (~280 kcal).",
      "Batido de frutos rojos con leche entera, avena certificada y miel (~280 kcal).",
      "Requesón con fruta, almendras y miel (~280 kcal).",
      "Tres tortitas de arroz con aguacate, tomate y huevo duro (~280 kcal).",
      "Uvas con queso curado, nueces y una tostada de pan sin gluten (~280 kcal).",
      "Batido de proteína con leche y plátano (~280 kcal).",
      "Infusión con orejones, almendras y nueces (~280 kcal).",
      "Barrita casera de dátiles y frutos secos con una pieza de fruta y nueces (~280 kcal).",
    ],
    comida: [
      "Doble pechuga de pollo a la plancha con arroz basmati, brócoli, aguacate y aceite de oliva (~820 kcal).",
      "Salmón al horno con boniato asado, quinoa, ensalada y aceite de oliva extra (~820 kcal).",
      "Lentejas estofadas con verduras, arroz, huevo duro y aceite de oliva extra (~820 kcal).",
      "Ración grande de pasta sin gluten con pollo, verduras salteadas, queso parmesano y aceite de oliva (~820 kcal).",
      "Merluza en salsa verde con patata cocida, ensalada y pan sin gluten (~820 kcal).",
      "Poke bowl grande de atún con doble arroz, edamame, aguacate y anacardos (~820 kcal).",
      "Curry de garbanzos y espinacas con arroz, leche de coco, anacardos y pan sin gluten (~820 kcal).",
      "Solomillo de cerdo con salsa de mostaza, verduras salteadas, arroz y pan sin gluten (~820 kcal).",
      "Ensalada grande de quinoa con atún, aguacate, tomate, huevo duro y aceite de oliva extra (~820 kcal).",
      "Ración grande de albóndigas en salsa de tomate con arroz, ensalada y pan sin gluten (~820 kcal).",
    ],
    merienda: [
      "Yogur griego con nueces, miel y granola sin gluten (~280 kcal).",
      "Dos tostadas de pan sin gluten con aguacate y huevo duro (~280 kcal).",
      "Queso fresco batido con fresas, miel y granola sin gluten (~280 kcal).",
      "Batido de cacao puro con leche entera, avena certificada, plátano y miel (~280 kcal).",
      "Almendras, pasas, orejones y una pieza de fruta (~280 kcal).",
      "Tortitas de maíz sin gluten con jamón cocido, tomate, aguacate y queso (~280 kcal).",
      "Hummus con tortitas de arroz, zanahoria, pepino y pimiento (~280 kcal).",
      "Batido de proteína con leche entera, fresas, avena certificada y miel (~280 kcal).",
      "Compota de manzana con nueces, canela, yogur y miel (~280 kcal).",
      "Dos barritas de cereales sin gluten con una pieza de fruta (~280 kcal).",
    ],
    cena: [
      "Tortilla de patatas (4 huevos) con ensalada verde, pan sin gluten y aceite de oliva extra (~820 kcal).",
      "Doble ración de pescado blanco al horno con verduras, patata y aceite de oliva extra (~820 kcal).",
      "Crema de calabaza con dos huevos duros, pan sin gluten y jamón serrano (~820 kcal).",
      "Ensalada grande de pollo, rúcula, tomate, queso feta, nueces y aguacate (~820 kcal).",
      "Revuelto de tres huevos con gambas, espárragos, pan sin gluten y aguacate (~820 kcal).",
      "Doble tofu salteado con verduras, arroz, anacardos y salsa de soja sin gluten (~820 kcal).",
      "Doble merluza en salsa verde con espárragos, patata y pan sin gluten (~820 kcal).",
      "Doble pechuga de pavo a la plancha con calabacín, zanahoria, arroz y aceite de oliva extra (~820 kcal).",
      "Vichyssoise con tres tostadas de pan sin gluten, jamón y queso (~820 kcal).",
      "Gazpacho andaluz con tortilla francesa de 4 huevos, pan sin gluten y jamón (~820 kcal).",
    ],
  },
};

const NOMBRES_DIAS = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"];

function buildPlanSemanas(kcal) {
  const pool = comidasPool[kcal];
  const semanas = [];
  for (let w = 0; w < 4; w++) {
    const dias = [];
    for (let i = 0; i < 7; i++) {
      const d = w * 7 + i;
      dias.push({
        dayKey: `${kcal}-${w}-${i}`,
        dia: NOMBRES_DIAS[i],
        comidas: [
          { label: "Desayuno", text: pool.desayuno[d % 10] },
          { label: "Media mañana", text: pool.mediaManana[(d + 3) % 10] },
          { label: "Comida", text: pool.comida[(d + 7) % 10] },
          { label: "Merienda", text: pool.merienda[(d + 5) % 10] },
          { label: "Cena", text: pool.cena[(d + 2) % 10] },
        ],
      });
    }
    semanas.push({ titulo: `Semana ${w + 1}`, dias });
  }
  return semanas;
}

const planesCalorias = {
  1500: {
    label: "1500 kcal/día",
    meta: "Déficit calórico moderado: pensado para complexiones menudas o poca actividad física. Consulta la calculadora para saber si te encaja.",
    semanas: buildPlanSemanas(1500),
  },
  1750: {
    label: "1750 kcal/día",
    meta: "Déficit calórico ligero, un paso intermedio entre 1500 y 2000 kcal para ajustar el ritmo de pérdida de peso.",
    semanas: buildPlanSemanas(1750),
  },
  2000: {
    label: "2000 kcal/día",
    meta: "Nivel de mantenimiento habitual para actividad física ligera-moderada en adultos de estatura y peso medios.",
    semanas: buildPlanSemanas(2000),
  },
  2250: {
    label: "2250 kcal/día",
    meta: "Ligero superávit o mantenimiento para complexiones algo mayores o actividad física moderada-alta.",
    semanas: buildPlanSemanas(2250),
  },
  2500: {
    label: "2500 kcal/día",
    meta: "Superávit o alta actividad física: pensado para complexiones grandes, entrenamiento frecuente o necesidades energéticas altas.",
    semanas: buildPlanSemanas(2500),
  },
  2750: {
    label: "2750 kcal/día",
    meta: "Superávit alto: pensado para complexiones muy grandes, entrenamiento intenso o necesidades energéticas muy elevadas.",
    semanas: buildPlanSemanas(2750),
  },
};

// Restaurantes investigados vía búsqueda web (fuentes: Celicidad, Celiaquita, FACE y
// asociaciones territoriales, Glutiful, FindMeGlutenFree, TheFork, Restaurant Guru,
// webs oficiales). Notas de Google Maps tal y como se encontraron en el momento de la
// investigación: pueden cambiar con el tiempo. "aprox: true" marca notas tomadas de un
// agregador (no un pantallazo directo de Google Maps) o con cifras que variaban algo
// entre fuentes — trátalas con un margen de ±0.1-0.2.
const restaurantesPorCiudad = {
  madrid: {
    label: "Madrid",
    restaurantes: [
      { nombre: "Ardemos Burger", nota: 4.8, resenas: 7200, zona: "Chamberí", desc: "Hamburguesería 100% sin gluten, sin riesgo de contaminación cruzada." },
      { nombre: "Pizza Natura", nota: 4.8, resenas: 2340, zona: "Centro", desc: "Pizzería 100% sin gluten con masa de mijo y quinoa." },
      { nombre: "El Japo Carranza", nota: 4.7, resenas: 2784, zona: "Chamberí / Trafalgar", desc: "Restaurante japonés con cocina íntegramente sin gluten." },
      { nombre: "Okashi Sanda", nota: 4.7, resenas: null, zona: "Malasaña / Universidad", desc: "Primer japonés sin gluten de Madrid, certificado FACE." },
      { nombre: "Bastardi Ristorante", nota: 4.7, resenas: 30, zona: "Malasaña", desc: "Italiano 100% sin gluten, avalado por asociación de celíacos.", aprox: true },
      { nombre: "Solo de Croquetas", nota: 4.4, resenas: 3600, zona: "Centro / Salamanca", desc: "Especialista en croquetas 100% sin gluten y sin lactosa." },
      { nombre: "As de Bastos", nota: 4.3, resenas: null, zona: "Bellas Vistas / Tetuán", desc: "Menú mediterráneo 100% sin gluten." },
      { nombre: "LaLina Bravas y Tapas", nota: 4.3, resenas: 3645, zona: "La Latina", desc: "Bar de tapas y bravas prácticamente 100% sin gluten." },
      { nombre: "Llagar La Llobera", nota: 4.2, resenas: null, zona: "Chamberí", desc: "Asturiano 100% apto celíacos: fabada, cachopo, croquetas." },
    ],
  },
  barcelona: {
    label: "Barcelona",
    restaurantes: [
      { nombre: "Aruku Sushi Gluten Free", nota: 4.7, resenas: 1185, zona: "Eixample", desc: "Japonés 100% sin gluten (sushi, gyozas), cerveza sin gluten de barril." },
      { nombre: "Copasetic", nota: 4.6, resenas: 1300, zona: "Eixample", desc: "Café-restaurante con amplia carta sin gluten (crepes, hamburguesas, brunch)." },
      { nombre: "ApriBocca", nota: 4.5, resenas: null, zona: "Poblenou", desc: "Italiano avalado por ACELCAT, pasta fresca y pizza sin gluten.", aprox: true },
      { nombre: "Jansana", nota: 4.5, resenas: 3800, zona: "Eixample", desc: "Pastelería-café 100% sin gluten: panes, pizzas, bollería y tartas.", aprox: true },
      { nombre: "En Ville", nota: 4.5, resenas: 3500, zona: "Raval", desc: "Carta 100% sin gluten certificada por ACELCAT, cocina catalana/mediterránea.", aprox: true },
      { nombre: "Messié Pizza Gluten Free", nota: 4.5, resenas: 3060, zona: "Gràcia", desc: "Pizzería italiana 100% sin gluten, sin riesgo de contaminación cruzada.", aprox: true },
      { nombre: "Out of China", nota: 4.4, resenas: null, zona: "Eixample", desc: "Chino avalado por ACELCAT, +90% de la carta sin gluten.", aprox: true },
      { nombre: "L'Arrosseria Xàtiva", nota: 4.4, resenas: null, zona: "Sant Antoni", desc: "Especialistas en paella/arroces, variedades sin gluten certificadas ACELCAT.", aprox: true },
      { nombre: "Senza Glutine by Grosso Napoletano", nota: 4.2, resenas: null, zona: "Eixample", desc: "Pizzería napolitana 100% sin gluten (masa de arroz, maíz y trigo sarraceno)." },
    ],
  },
  valencia: {
    label: "Valencia",
    restaurantes: [
      { nombre: "Carlotes Café", nota: 4.9, resenas: 87, zona: "Ensanche / Extramurs", desc: "Cafetería 100% sin gluten certificada segura, personal formado en celiaquía." },
      { nombre: "Malkebien", nota: 4.7, resenas: 1446, zona: "Zona universitaria", desc: "Socio colaborador ACECOVA, pan y cerveza sin gluten." },
      { nombre: "Disidente", nota: 4.7, resenas: 431, zona: "Ensanche", desc: "Vegetariano con opciones sin gluten y gestión cuidadosa de alergias." },
      { nombre: "Civera Marisquería", nota: 4.6, resenas: 2000, zona: "Sant Francesc / centro", desc: "Marisquería histórica (desde los 60) incluida en el listado seguro de ACECOVA." },
      { nombre: "El Miracle", nota: 4.5, resenas: 2600, zona: "Pla del Remei / Gran Vía", desc: "Primer restaurante 100% sin gluten certificado por ACECOVA en la Comunidad Valenciana." },
      { nombre: "La Pappardella", nota: 4.5, resenas: 2200, zona: "La Seu", desc: "Italiana con carta asesorada por la asociación de celíacos." },
      { nombre: "Kuzina", nota: 4.5, resenas: 2000, zona: "Ciutat Vella, cerca de Ruzafa", desc: "Griega con amplia oferta sin gluten señalizada." },
      { nombre: "Casa Carmela", nota: 4.4, resenas: 8900, zona: "Malvarrosa", desc: "Icónica arrocería centenaria con acuerdo ACECOVA, pan sin gluten." },
      { nombre: "Al Pomodoro", nota: 4.4, resenas: 1300, zona: "La Xerea / Ciutat Vella", desc: "Pizzería italiana artesanal con opciones sin gluten, listada por Celicidad." },
      { nombre: "Mey Chen", nota: 4.3, resenas: 2700, zona: "Benimaclet", desc: "China avalada por ACECOVA, comanda diferenciada por plato." },
      { nombre: "LaLoLa Restaurante", nota: 4.3, resenas: 3150, zona: "La Seu, junto a la Catedral", desc: "Toda la carta de arroces y tapas es sin gluten (salvo el pan).", aprox: true },
      { nombre: "Mállalo X", nota: 4.1, resenas: 275, zona: "Mercado Central / Velluters", desc: "Acreditado por ACECOVA como local seguro." },
    ],
  },
  sevilla: {
    label: "Sevilla",
    restaurantes: [
      { nombre: "Restaurante Marroquí La Alcoba", nota: 4.8, resenas: 876, zona: "Santa Clara", desc: "Cocina marroquí con pastela y platos sin gluten, personal atento a intolerancias." },
      { nombre: "Barra Baja", nota: 4.7, resenas: 600, zona: "Casco Antiguo", desc: "Cocina de mercado andaluza de autor, miembro de la Red Sevilla Sin Gluten.", aprox: true },
      { nombre: "Acento - Social Eatery", nota: 4.7, resenas: 800, zona: "El Arenal / Casco Antiguo", desc: "Mediterráneo-internacional con atención específica a comensales celíacos." },
      { nombre: "Petit Comité", nota: 4.5, resenas: 2465, zona: "Casco Antiguo", desc: "Tapas de calidad, miembro de la Red Sevilla Sin Gluten-ASPROCESE." },
      { nombre: "Al Solito Posto", nota: 4.4, resenas: 4500, zona: "Alameda de Hércules", desc: "Italiano histórico homologado por la Asociación de Celíacos de Sevilla." },
      { nombre: "Señora Pan", nota: 4.4, resenas: null, zona: "Casco Antiguo", desc: "Restaurante 100% sin gluten, fusión español-venezolana." },
      { nombre: "Orfeo", nota: 4.2, resenas: 811, zona: "Casco Antiguo", desc: "Café-bar tranquilo, miembro de la Red Sevilla Sin Gluten-ASPROCESE." },
      { nombre: "Estragón", nota: 4.1, resenas: null, zona: "El Porvenir", desc: "Carta 100% sin gluten sin riesgo de contaminación cruzada, tapas y raciones." },
      { nombre: "Habanita", nota: 4.1, resenas: null, zona: "Casco Antiguo, junto a Plaza Alfalfa", desc: "Vegetariano/cubano con opciones sin gluten, más de 20 años de trayectoria." },
    ],
  },
  bilbao: {
    label: "Bilbao",
    restaurantes: [
      { nombre: "Casa Leotta – Pozas", nota: 4.7, resenas: null, zona: "Pozas / Abando", desc: "Pinsas y pasta 100% sin gluten, asesorados por EZE (Celíacos de Euskadi)." },
      { nombre: "Casa Leotta – Ajuriaguerra", nota: 4.6, resenas: 2192, zona: "Ajuriaguerra / Abando", desc: "Pinsas y pasta sin gluten dedicadas, avalado por EZE." },
      { nombre: "Kalí Órexi by Labocatorio", nota: 4.6, resenas: 1500, zona: "Abando (Fernández del Campo)", desc: "Gastrobar griego-mediterráneo con platos marcados sin gluten en carta." },
      { nombre: "Arraiz Asador", nota: 4.5, resenas: 1450, zona: "Arraiz (cerca de Artxanda)", desc: "Asador con certificación oficial FACE desde 2016.", aprox: true },
      { nombre: "Ahoan", nota: 4.2, resenas: null, zona: "Plaza Nueva / Casco Viejo", desc: "Bar de pintxos con cocina separada, dueños celíacos." },
      { nombre: "El Informal", nota: 4.2, resenas: 606, zona: "Indautxu / Ensanche", desc: "Mediterráneo-vasco con menú adaptado sin gluten y opciones vegetarianas." },
      { nombre: "Mandoya", nota: 4.1, resenas: null, zona: "Casco Viejo", desc: "Usa harina de garbanzo desde los años 90, amplio conocimiento de la celiaquía.", aprox: true },
      { nombre: "La Lonja de Olabeaga", nota: 4.0, resenas: null, zona: "Olabeaga", desc: "Cocina tradicional vasca a la brasa avalada por FACE desde 2024." },
      { nombre: "Larruzz", nota: 4.0, resenas: null, zona: "Uribitarte (junto al Guggenheim)", desc: "Certificado por EZE, protocolos anti-contaminación cruzada, arroces." },
    ],
  },
  malaga: {
    label: "Málaga",
    restaurantes: [
      { nombre: "Sushi Flower", nota: 4.8, resenas: 605, zona: "Perchel / Teatinos", desc: "Carta 98% sin gluten, extremo cuidado con la contaminación cruzada.", aprox: true },
      { nombre: "Reviv Café", nota: 4.8, resenas: 429, zona: "Centro Histórico", desc: "Cafetería 100% sin gluten y vegana, certificada por la Red Málaga Sin Gluten." },
      { nombre: "La Plancha Taberna", nota: 4.7, resenas: 140, zona: "El Perchel", desc: "Carta 100% sin gluten, certificada por la red Málaga Sin Gluten.", aprox: true },
      { nombre: "Mesón Mariano", nota: 4.7, resenas: 3000, zona: "Centro", desc: "Taberna tradicional desde 1988 que señala el gluten en cada plato." },
      { nombre: "Bibra Real Food Teatinos", nota: 4.6, resenas: 1098, zona: "Teatinos-Universidad", desc: "Red Málaga Sin Gluten, poke bowls y ensaladas sin contaminación cruzada." },
      { nombre: "El Taller de Larios 10", nota: 4.6, resenas: null, zona: "Centro (Calle Larios)", desc: "Restaurante en azotea con categoría sin gluten reconocida en TheFork." },
      { nombre: "Osteria Angelino dal 1899", nota: 4.6, resenas: 3659, zona: "Centro", desc: "Italiano con pasta sin gluten y alérgenos claramente marcados en carta." },
      { nombre: "Maldonado 21", nota: 4.5, resenas: 830, zona: "Ciudad Jardín", desc: "Especialista en fritura sin gluten con utensilios y platos separados." },
      { nombre: "El Tapeo de Cervantes", nota: 4.3, resenas: null, zona: "Centro", desc: "Bar de tapas de autor que marca el gluten en el menú." },
      { nombre: "Los Mellizos Soho", nota: 4.1, resenas: 2790, zona: "Soho", desc: "100% sin gluten certificado ACEMA, especializado en pescaíto frito y marisco.", aprox: true },
    ],
  },
  zaragoza: {
    label: "Zaragoza",
    restaurantes: [
      { nombre: "Labamba", nota: 4.8, resenas: 647, zona: "Casco Antiguo / Centro", desc: "Menú degustación de 6 pasos 100% sin gluten, cambia cada temporada." },
      { nombre: "Urbanita Gastrobar", nota: 4.8, resenas: null, zona: "Centro", desc: "Gastrobar 100% sin gluten con certificación oficial." },
      { nombre: "Restaurante Isla Sicilia (Con y Sin Gluten)", nota: 4.7, resenas: 1182, zona: "Casco Antiguo (Pl. del Pilar)", desc: "Italiano con dos cocinas separadas para evitar contaminación cruzada." },
      { nombre: "La Jaula de Grillos", nota: 4.6, resenas: null, zona: "Casco Antiguo", desc: "Primer establecimiento 100% sin gluten de Aragón (2016)." },
      { nombre: "Restaurante Baobab", nota: 4.6, resenas: 4079, zona: "Romareda", desc: "Vegetariano histórico (desde 2005) afiliado a la asociación de celíacos." },
      { nombre: "Mononoke Board Game Café", nota: 4.5, resenas: null, zona: "Centro / Delicias", desc: "Cafetería-ludoteca con carta de pizzas y cervezas artesanales sin gluten." },
      { nombre: "El Disfrutón", nota: 4.5, resenas: 690, zona: "Casco Histórico", desc: "Miembro de la Asociación Celíaca Aragonesa (ACA), carta mediterránea adaptada." },
      { nombre: "El Truco", nota: 4.4, resenas: 2000, zona: "El Tubo / Casco Antiguo", desc: "Bar de tapas 100% sin gluten, premiado varios años por sus croquetas." },
      { nombre: "Costa 8 Gastrobar", nota: 4.3, resenas: null, zona: "Centro", desc: "Certificado por la Asociación Celíaca de Aragón (ACA)." },
      { nombre: "La Antilla", nota: 4.3, resenas: 475, zona: "Varios locales", desc: "Pan sin gluten, muy recomendada avisando con antelación." },
      { nombre: "BuleBar Zentro", nota: 4.1, resenas: 1664, zona: "Centro", desc: "Arrocería/paellas con especialidades sin gluten bajo petición." },
    ],
  },
  alicante: {
    label: "Alicante",
    restaurantes: [
      { nombre: "Distópico", nota: 4.9, resenas: 380, zona: "Centro", desc: "Cocina mediterránea de fusión; sus croquetas llevan el sello de garantía ACECOVA." },
      { nombre: "Punto de Uva", nota: 4.8, resenas: null, zona: "Centro", desc: "Vinoteca/tapas de autor 100% sin gluten avalada por ACECOVA." },
      { nombre: "Kazoku Sushi Restaurant", nota: 4.7, resenas: 250, zona: "Cabo de las Huertas", desc: "Japonés con carta específica sin gluten y control de contaminación cruzada." },
      { nombre: "Vértice Cervecería Bulevar", nota: 4.6, resenas: 100, zona: "Bulevar / Ciudad de Asís", desc: "Más del 80% de la carta apta para celíacos." },
      { nombre: "La Taverna dell'Artista", nota: 4.5, resenas: 1700, zona: "Centro (Pl. San Cristóbal)", desc: "Pizzería italiana 100% sin gluten certificada por ACECOVA.", aprox: true },
      { nombre: "Rice&Bones", nota: 4.5, resenas: 100, zona: "Centro", desc: "Único arrocero de Alicante certificado 100% sin gluten por ACECOVA." },
      { nombre: "La Taverna del Racó del Pla", nota: 4.5, resenas: 650, zona: "Centro (C. San Mateo)", desc: "Taberna urbana de arroces y tapas; pan sin gluten y protocolos de seguridad." },
      { nombre: "Apache Burger Grill", nota: 4.4, resenas: 800, zona: "Playa de San Juan", desc: "Hamburguesería premiada, freidora y panes sin gluten separados.", aprox: true },
      { nombre: "Oz Gastroclub", nota: 4.4, resenas: 540, zona: "Playa de San Juan", desc: "Carta prácticamente 100% sin gluten certificada por ACECOVA." },
      { nombre: "Askuabarra Alicante", nota: 4.4, resenas: 200, zona: "Centro", desc: "Bar de pinchos/tapas con amplia oferta sin gluten." },
    ],
  },
  castellon: {
    label: "Castellón",
    restaurantes: [
      { nombre: "Can Celiac", nota: 4.8, resenas: 195, zona: "Centro", desc: "Panadería-café 100% sin gluten, elaboración diaria sin contaminación cruzada." },
      { nombre: "GoodFood Gastro Bar", nota: 4.8, resenas: 25, zona: "Centro", desc: "Gastrobar pequeño con toda la carta 100% sin gluten.", aprox: true },
      { nombre: "L'Etrusco", nota: 4.6, resenas: 1700, zona: "Centro", desc: "Italiano avalado por ACECOVA, elaboración y carta adaptadas.", aprox: true },
      { nombre: "Little Thai Castellón", nota: 4.6, resenas: null, zona: "Centro (Av. Rei En Jaume)", desc: "Cocina tailandesa con platos sin gluten marcados en carta." },
      { nombre: "Peltre Cuina Mexicana", nota: 4.6, resenas: 1060, zona: "Centro", desc: "Cocina mexicana muy bien valorada, con opciones sin gluten cuidadas." },
      { nombre: "Corpore Sano Duo", nota: 4.5, resenas: 183, zona: "Centro", desc: "Restaurante 100% sin gluten certificado por ACECOVA, cocina saludable." },
      { nombre: "Le Otto Sin Gluten", nota: 4.5, resenas: null, zona: "Centro", desc: "Pizzería 100% sin gluten, horno exclusivo sin riesgo de trazas." },
      { nombre: "El Colmado", nota: 4.4, resenas: 130, zona: "Junto al Mercado Central", desc: "Taberna con utensilios duplicados para evitar contaminación cruzada." },
      { nombre: "Lino Gastronomic", nota: 4.4, resenas: null, zona: "Casco histórico", desc: "Carta de arroces con opciones aptas para celíacos." },
    ],
  },
};

// Tiendas cuyo negocio principal es la venta de productos sin gluten (no
// supermercados generalistas). Investigadas vía búsqueda web en septiembre de
// 2026: nombres y ubicaciones verificados, pero las notas de Google y el nº de
// reseñas proceden en su mayoría de agregadores de búsqueda, no de una consulta
// directa a Google Maps — trátalas como orientativas ("aprox: true" cuando la
// fuente lo advierte explícitamente). "web: null" significa que no se encontró
// un sitio oficial propio confirmado con confianza razonable.
const tiendasEspecializadas = [
  {
    nombre: "Artediet",
    tipo: "Física",
    ciudad: "Madrid",
    desc: "Panadería y pastelería 100% sin gluten: pan, bollería, dulces y salados.",
    nota: 4.8,
    resenas: 185,
    web: "https://www.artediet.es/",
  },
  {
    nombre: "Gluten Tag",
    tipo: "Física",
    ciudad: "Barcelona (Gràcia)",
    desc: "Obrador sin gluten especializado en bollería, pan y dulces.",
    nota: 4.8,
    resenas: 159,
    web: "https://www.glutentag.cat",
  },
  {
    nombre: "Celiacs & Co",
    tipo: "Física",
    ciudad: "Barcelona (La Sagrera)",
    desc: "Supermercado especializado sin gluten (también sin lactosa y opciones veganas).",
    nota: 4.8,
    resenas: null,
    aprox: true,
    web: "https://celiacsandco.com/",
  },
  {
    nombre: "Glutery",
    tipo: "Física",
    ciudad: "Barcelona (Gràcia)",
    desc: "Café-obrador sin gluten certificado por Celíacs Catalunya, conocido por empanadas y focaccia.",
    nota: 4.7,
    resenas: null,
    aprox: true,
    web: null,
  },
  {
    nombre: "Maná Productos Sin Gluten",
    tipo: "Física y online",
    ciudad: "Madrid (Salamanca)",
    desc: "Supermercado especializado sin gluten con más de 600 referencias de varias marcas.",
    nota: 4.2,
    resenas: 121,
    web: "https://www.manaproductossingluten.com/",
  },
  {
    nombre: "Celicioso",
    tipo: "Física",
    ciudad: "Madrid (varios locales, también Marbella y Palma)",
    desc: "Pastelería-cafetería 100% sin gluten: bollería americana, dulce y salado.",
    nota: 3.9,
    resenas: null,
    aprox: true,
    web: null,
  },
  {
    nombre: "Sana Locura Gluten Free Bakery",
    tipo: "Física",
    ciudad: "Barcelona (Sant Gervasi)",
    desc: "Panadería y pastelería 100% sin gluten.",
    nota: 3.5,
    resenas: 84,
    web: "https://sanalocura.es/",
  },
  {
    nombre: "La Celiacoteca",
    tipo: "Física",
    ciudad: "Madrid / Alcalá de Henares",
    desc: "Obrador 100% sin gluten: panadería, bollería y masas saladas.",
    nota: null,
    resenas: null,
    web: "https://www.laceliacoteca.com/index.html",
  },
  {
    nombre: "Món Celíac",
    tipo: "Física y online",
    ciudad: "Barcelona",
    desc: "Obrador 100% sin gluten: pan, dulces y snacks, con envío a la península.",
    nota: null,
    resenas: null,
    web: "https://monceliac.com/",
  },
  {
    nombre: "Celikatessen",
    tipo: "Física",
    ciudad: "Madrid (Mercado de Pacífico)",
    desc: "Panadería y repostería ecológica sin gluten y sin lácteos.",
    nota: null,
    resenas: null,
    web: null,
  },
  {
    nombre: "Celicientos",
    tipo: "Física",
    ciudad: "Valencia",
    desc: "Panadería-cafetería 100% sin gluten, dulce y salado, con reparto a domicilio.",
    nota: null,
    resenas: null,
    web: "https://celicientos.com/",
  },
  {
    nombre: "El Obrador del Celíaco",
    tipo: "Física",
    ciudad: "Valencia",
    desc: "Panadería y pastelería sin gluten y sin lactosa: pan rústico, fartons, tartas.",
    nota: null,
    resenas: null,
    web: null,
  },
  {
    nombre: "Panceliac",
    tipo: "Online",
    ciudad: "Envío a toda España",
    desc: "Panadería, bollería y alimentación sin gluten con envío a domicilio.",
    nota: null,
    resenas: null,
    web: "https://panceliac.com/",
  },
  {
    nombre: "Glutenfreeshop.es",
    tipo: "Online",
    ciudad: "Envío a la península",
    desc: "Selección gourmet de alimentos ecológicos sin gluten, suplementos y libros.",
    nota: null,
    resenas: null,
    web: "https://glutenfreeshop.es/",
  },
];
